// Code generated by MockGen. DO NOT EDIT.
// Source: api.go
//
// Generated by this command:
//
//	mockgen -source=api.go -destination=mock/api.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	types "github.com/baking-bad/noble-indexer/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockApi is a mock of Api interface.
type MockApi struct {
	ctrl     *gomock.Controller
	recorder *MockApiMockRecorder
	isgomock struct{}
}

// MockApiMockRecorder is the mock recorder for MockApi.
type MockApiMockRecorder struct {
	mock *MockApi
}

// NewMockApi creates a new mock instance.
func NewMockApi(ctrl *gomock.Controller) *MockApi {
	mock := &MockApi{ctrl: ctrl}
	mock.recorder = &MockApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApi) EXPECT() *MockApiMockRecorder {
	return m.recorder
}

// Block mocks base method.
func (m *MockApi) Block(ctx context.Context, level types.Level) (types.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Block", ctx, level)
	ret0, _ := ret[0].(types.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Block indicates an expected call of Block.
func (mr *MockApiMockRecorder) Block(ctx, level any) *MockApiBlockCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Block", reflect.TypeOf((*MockApi)(nil).Block), ctx, level)
	return &MockApiBlockCall{Call: call}
}

// MockApiBlockCall wrap *gomock.Call
type MockApiBlockCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockApiBlockCall) Return(arg0 types.Block, arg1 error) *MockApiBlockCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockApiBlockCall) Do(f func(context.Context, types.Level) (types.Block, error)) *MockApiBlockCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockApiBlockCall) DoAndReturn(f func(context.Context, types.Level) (types.Block, error)) *MockApiBlockCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BlockBulk mocks base method.
func (m *MockApi) BlockBulk(ctx context.Context, levels ...types.Level) ([]types.BlockData, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range levels {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BlockBulk", varargs...)
	ret0, _ := ret[0].([]types.BlockData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockBulk indicates an expected call of BlockBulk.
func (mr *MockApiMockRecorder) BlockBulk(ctx any, levels ...any) *MockApiBlockBulkCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, levels...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockBulk", reflect.TypeOf((*MockApi)(nil).BlockBulk), varargs...)
	return &MockApiBlockBulkCall{Call: call}
}

// MockApiBlockBulkCall wrap *gomock.Call
type MockApiBlockBulkCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockApiBlockBulkCall) Return(arg0 []types.BlockData, arg1 error) *MockApiBlockBulkCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockApiBlockBulkCall) Do(f func(context.Context, ...types.Level) ([]types.BlockData, error)) *MockApiBlockBulkCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockApiBlockBulkCall) DoAndReturn(f func(context.Context, ...types.Level) ([]types.BlockData, error)) *MockApiBlockBulkCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Head mocks base method.
func (m *MockApi) Head(ctx context.Context) (types.Level, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Head", ctx)
	ret0, _ := ret[0].(types.Level)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Head indicates an expected call of Head.
func (mr *MockApiMockRecorder) Head(ctx any) *MockApiHeadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Head", reflect.TypeOf((*MockApi)(nil).Head), ctx)
	return &MockApiHeadCall{Call: call}
}

// MockApiHeadCall wrap *gomock.Call
type MockApiHeadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockApiHeadCall) Return(arg0 types.Level, arg1 error) *MockApiHeadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockApiHeadCall) Do(f func(context.Context) (types.Level, error)) *MockApiHeadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockApiHeadCall) DoAndReturn(f func(context.Context) (types.Level, error)) *MockApiHeadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Storage mocks base method.
func (m *MockApi) Storage(ctx context.Context, requestData []types.StorageRequest) ([]types.Hex, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Storage", ctx, requestData)
	ret0, _ := ret[0].([]types.Hex)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Storage indicates an expected call of Storage.
func (mr *MockApiMockRecorder) Storage(ctx, requestData any) *MockApiStorageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Storage", reflect.TypeOf((*MockApi)(nil).Storage), ctx, requestData)
	return &MockApiStorageCall{Call: call}
}

// MockApiStorageCall wrap *gomock.Call
type MockApiStorageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockApiStorageCall) Return(arg0 []types.Hex, arg1 error) *MockApiStorageCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockApiStorageCall) Do(f func(context.Context, []types.StorageRequest) ([]types.Hex, error)) *MockApiStorageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockApiStorageCall) DoAndReturn(f func(context.Context, []types.StorageRequest) ([]types.Hex, error)) *MockApiStorageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TokenMetadataBulk mocks base method.
func (m *MockApi) TokenMetadataBulk(ctx context.Context, request []types.TokenMetadataRequest) (map[uint64]types.TokenMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenMetadataBulk", ctx, request)
	ret0, _ := ret[0].(map[uint64]types.TokenMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TokenMetadataBulk indicates an expected call of TokenMetadataBulk.
func (mr *MockApiMockRecorder) TokenMetadataBulk(ctx, request any) *MockApiTokenMetadataBulkCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenMetadataBulk", reflect.TypeOf((*MockApi)(nil).TokenMetadataBulk), ctx, request)
	return &MockApiTokenMetadataBulkCall{Call: call}
}

// MockApiTokenMetadataBulkCall wrap *gomock.Call
type MockApiTokenMetadataBulkCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockApiTokenMetadataBulkCall) Return(arg0 map[uint64]types.TokenMetadata, arg1 error) *MockApiTokenMetadataBulkCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockApiTokenMetadataBulkCall) Do(f func(context.Context, []types.TokenMetadataRequest) (map[uint64]types.TokenMetadata, error)) *MockApiTokenMetadataBulkCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockApiTokenMetadataBulkCall) DoAndReturn(f func(context.Context, []types.TokenMetadataRequest) (map[uint64]types.TokenMetadata, error)) *MockApiTokenMetadataBulkCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
