// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// CallTypeCall is a CallType of type call.
	CallTypeCall CallType = "call"
	// CallTypeDelegatecall is a CallType of type delegatecall.
	CallTypeDelegatecall CallType = "delegatecall"
	// CallTypeStaticcall is a CallType of type staticcall.
	CallTypeStaticcall CallType = "staticcall"
	// CallTypeCallcode is a CallType of type callcode.
	CallTypeCallcode CallType = "callcode"
)

var ErrInvalidCallType = fmt.Errorf("not a valid CallType, try [%s]", strings.Join(_CallTypeNames, ", "))

var _CallTypeNames = []string{
	string(CallTypeCall),
	string(CallTypeDelegatecall),
	string(CallTypeStaticcall),
	string(CallTypeCallcode),
}

// CallTypeNames returns a list of possible string values of CallType.
func CallTypeNames() []string {
	tmp := make([]string, len(_CallTypeNames))
	copy(tmp, _CallTypeNames)
	return tmp
}

// CallTypeValues returns a list of the values for CallType
func CallTypeValues() []CallType {
	return []CallType{
		CallTypeCall,
		CallTypeDelegatecall,
		CallTypeStaticcall,
		CallTypeCallcode,
	}
}

// String implements the Stringer interface.
func (x CallType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x CallType) IsValid() bool {
	_, err := ParseCallType(string(x))
	return err == nil
}

var _CallTypeValue = map[string]CallType{
	"call":         CallTypeCall,
	"delegatecall": CallTypeDelegatecall,
	"staticcall":   CallTypeStaticcall,
	"callcode":     CallTypeCallcode,
}

// ParseCallType attempts to convert a string to a CallType.
func ParseCallType(name string) (CallType, error) {
	if x, ok := _CallTypeValue[name]; ok {
		return x, nil
	}
	return CallType(""), fmt.Errorf("%s is %w", name, ErrInvalidCallType)
}

// MarshalText implements the text marshaller method.
func (x CallType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *CallType) UnmarshalText(text []byte) error {
	tmp, err := ParseCallType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var errCallTypeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *CallType) Scan(value interface{}) (err error) {
	if value == nil {
		*x = CallType("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseCallType(v)
	case []byte:
		*x, err = ParseCallType(string(v))
	case CallType:
		*x = v
	case *CallType:
		if v == nil {
			return errCallTypeNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errCallTypeNilPtr
		}
		*x, err = ParseCallType(*v)
	default:
		return errors.New("invalid type for CallType")
	}

	return
}

// Value implements the driver Valuer interface.
func (x CallType) Value() (driver.Value, error) {
	return x.String(), nil
}
