// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// Homestead is a EVMVersion of type homestead.
	Homestead EVMVersion = "homestead"
	// TangerineWhistle is a EVMVersion of type tangerineWhistle.
	TangerineWhistle EVMVersion = "tangerineWhistle"
	// SpuriousDragon is a EVMVersion of type spuriousDragon.
	SpuriousDragon EVMVersion = "spuriousDragon"
	// Byzantium is a EVMVersion of type byzantium.
	Byzantium EVMVersion = "byzantium"
	// Constantinople is a EVMVersion of type constantinople.
	Constantinople EVMVersion = "constantinople"
	// Petersburg is a EVMVersion of type petersburg.
	Petersburg EVMVersion = "petersburg"
	// Istanbul is a EVMVersion of type istanbul.
	Istanbul EVMVersion = "istanbul"
	// Berlin is a EVMVersion of type berlin.
	Berlin EVMVersion = "berlin"
	// London is a EVMVersion of type london.
	London EVMVersion = "london"
	// Paris is a EVMVersion of type paris.
	Paris EVMVersion = "paris"
	// Shanghai is a EVMVersion of type shanghai.
	Shanghai EVMVersion = "shanghai"
	// Cancun is a EVMVersion of type cancun.
	Cancun EVMVersion = "cancun"
	// Prague is a EVMVersion of type prague.
	Prague EVMVersion = "prague"
)

var ErrInvalidEVMVersion = fmt.Errorf("not a valid EVMVersion, try [%s]", strings.Join(_EVMVersionNames, ", "))

var _EVMVersionNames = []string{
	string(Homestead),
	string(TangerineWhistle),
	string(SpuriousDragon),
	string(Byzantium),
	string(Constantinople),
	string(Petersburg),
	string(Istanbul),
	string(Berlin),
	string(London),
	string(Paris),
	string(Shanghai),
	string(Cancun),
	string(Prague),
}

// EVMVersionNames returns a list of possible string values of EVMVersion.
func EVMVersionNames() []string {
	tmp := make([]string, len(_EVMVersionNames))
	copy(tmp, _EVMVersionNames)
	return tmp
}

// EVMVersionValues returns a list of the values for EVMVersion
func EVMVersionValues() []EVMVersion {
	return []EVMVersion{
		Homestead,
		TangerineWhistle,
		SpuriousDragon,
		Byzantium,
		Constantinople,
		Petersburg,
		Istanbul,
		Berlin,
		London,
		Paris,
		Shanghai,
		Cancun,
		Prague,
	}
}

// String implements the Stringer interface.
func (x EVMVersion) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x EVMVersion) IsValid() bool {
	_, err := ParseEVMVersion(string(x))
	return err == nil
}

var _EVMVersionValue = map[string]EVMVersion{
	"homestead":        Homestead,
	"tangerineWhistle": TangerineWhistle,
	"spuriousDragon":   SpuriousDragon,
	"byzantium":        Byzantium,
	"constantinople":   Constantinople,
	"petersburg":       Petersburg,
	"istanbul":         Istanbul,
	"berlin":           Berlin,
	"london":           London,
	"paris":            Paris,
	"shanghai":         Shanghai,
	"cancun":           Cancun,
	"prague":           Prague,
}

// ParseEVMVersion attempts to convert a string to a EVMVersion.
func ParseEVMVersion(name string) (EVMVersion, error) {
	if x, ok := _EVMVersionValue[name]; ok {
		return x, nil
	}
	return EVMVersion(""), fmt.Errorf("%s is %w", name, ErrInvalidEVMVersion)
}

// MarshalText implements the text marshaller method.
func (x EVMVersion) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *EVMVersion) UnmarshalText(text []byte) error {
	tmp, err := ParseEVMVersion(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var errEVMVersionNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *EVMVersion) Scan(value interface{}) (err error) {
	if value == nil {
		*x = EVMVersion("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseEVMVersion(v)
	case []byte:
		*x, err = ParseEVMVersion(string(v))
	case EVMVersion:
		*x = v
	case *EVMVersion:
		if v == nil {
			return errEVMVersionNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errEVMVersionNilPtr
		}
		*x, err = ParseEVMVersion(*v)
	default:
		return errors.New("invalid type for EVMVersion")
	}

	return
}

// Value implements the driver Valuer interface.
func (x EVMVersion) Value() (driver.Value, error) {
	return x.String(), nil
}
