// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// Success is a MetadataStatus of type success.
	Success MetadataStatus = "success"
	// Failed is a MetadataStatus of type failed.
	Failed MetadataStatus = "failed"
	// Pending is a MetadataStatus of type pending.
	Pending MetadataStatus = "pending"
)

var ErrInvalidMetadataStatus = fmt.Errorf("not a valid MetadataStatus, try [%s]", strings.Join(_MetadataStatusNames, ", "))

var _MetadataStatusNames = []string{
	string(Success),
	string(Failed),
	string(Pending),
}

// MetadataStatusNames returns a list of possible string values of MetadataStatus.
func MetadataStatusNames() []string {
	tmp := make([]string, len(_MetadataStatusNames))
	copy(tmp, _MetadataStatusNames)
	return tmp
}

// MetadataStatusValues returns a list of the values for MetadataStatus
func MetadataStatusValues() []MetadataStatus {
	return []MetadataStatus{
		Success,
		Failed,
		Pending,
	}
}

// String implements the Stringer interface.
func (x MetadataStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x MetadataStatus) IsValid() bool {
	_, err := ParseMetadataStatus(string(x))
	return err == nil
}

var _MetadataStatusValue = map[string]MetadataStatus{
	"success": Success,
	"failed":  Failed,
	"pending": Pending,
}

// ParseMetadataStatus attempts to convert a string to a MetadataStatus.
func ParseMetadataStatus(name string) (MetadataStatus, error) {
	if x, ok := _MetadataStatusValue[name]; ok {
		return x, nil
	}
	return MetadataStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidMetadataStatus)
}

// MarshalText implements the text marshaller method.
func (x MetadataStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *MetadataStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseMetadataStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *MetadataStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errMetadataStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *MetadataStatus) Scan(value interface{}) (err error) {
	if value == nil {
		*x = MetadataStatus("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseMetadataStatus(v)
	case []byte:
		*x, err = ParseMetadataStatus(string(v))
	case MetadataStatus:
		*x = v
	case *MetadataStatus:
		if v == nil {
			return errMetadataStatusNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errMetadataStatusNilPtr
		}
		*x, err = ParseMetadataStatus(*v)
	default:
		return errors.New("invalid type for MetadataStatus")
	}

	return
}

// Value implements the driver Valuer interface.
func (x MetadataStatus) Value() (driver.Value, error) {
	return x.String(), nil
}
