// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// EIP1167 is a ProxyType of type EIP1167.
	EIP1167 ProxyType = "EIP1167"
	// EIP7760 is a ProxyType of type EIP7760.
	EIP7760 ProxyType = "EIP7760"
	// EIP7702 is a ProxyType of type EIP7702.
	EIP7702 ProxyType = "EIP7702"
	// EIP1967 is a ProxyType of type EIP1967.
	EIP1967 ProxyType = "EIP1967"
	// Custom is a ProxyType of type custom.
	Custom ProxyType = "custom"
	// CloneWithImmutableArgs is a ProxyType of type clone_with_immutable_args.
	CloneWithImmutableArgs ProxyType = "clone_with_immutable_args"
)

var ErrInvalidProxyType = fmt.Errorf("not a valid ProxyType, try [%s]", strings.Join(_ProxyTypeNames, ", "))

var _ProxyTypeNames = []string{
	string(EIP1167),
	string(EIP7760),
	string(EIP7702),
	string(EIP1967),
	string(Custom),
	string(CloneWithImmutableArgs),
}

// ProxyTypeNames returns a list of possible string values of ProxyType.
func ProxyTypeNames() []string {
	tmp := make([]string, len(_ProxyTypeNames))
	copy(tmp, _ProxyTypeNames)
	return tmp
}

// ProxyTypeValues returns a list of the values for ProxyType
func ProxyTypeValues() []ProxyType {
	return []ProxyType{
		EIP1167,
		EIP7760,
		EIP7702,
		EIP1967,
		Custom,
		CloneWithImmutableArgs,
	}
}

// String implements the Stringer interface.
func (x ProxyType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ProxyType) IsValid() bool {
	_, err := ParseProxyType(string(x))
	return err == nil
}

var _ProxyTypeValue = map[string]ProxyType{
	"EIP1167":                   EIP1167,
	"EIP7760":                   EIP7760,
	"EIP7702":                   EIP7702,
	"EIP1967":                   EIP1967,
	"custom":                    Custom,
	"clone_with_immutable_args": CloneWithImmutableArgs,
}

// ParseProxyType attempts to convert a string to a ProxyType.
func ParseProxyType(name string) (ProxyType, error) {
	if x, ok := _ProxyTypeValue[name]; ok {
		return x, nil
	}
	return ProxyType(""), fmt.Errorf("%s is %w", name, ErrInvalidProxyType)
}

// MarshalText implements the text marshaller method.
func (x ProxyType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ProxyType) UnmarshalText(text []byte) error {
	tmp, err := ParseProxyType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ProxyType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errProxyTypeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *ProxyType) Scan(value interface{}) (err error) {
	if value == nil {
		*x = ProxyType("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseProxyType(v)
	case []byte:
		*x, err = ParseProxyType(string(v))
	case ProxyType:
		*x = v
	case *ProxyType:
		if v == nil {
			return errProxyTypeNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errProxyTypeNilPtr
		}
		*x, err = ParseProxyType(*v)
	default:
		return errors.New("invalid type for ProxyType")
	}

	return
}

// Value implements the driver Valuer interface.
func (x ProxyType) Value() (driver.Value, error) {
	return x.String(), nil
}
