// Code generated by go-enum DO NOT EDIT.
// Version: 0.5.7
// Revision: bf63e108589bbd2327b13ec2c5da532aad234029
// Build Date: 2023-07-25T23:27:55Z
// Built By: goreleaser

package types

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// New is a ProxyStatus of type new.
	New ProxyStatus = "new"
	// Resolved is a ProxyStatus of type resolved.
	Resolved ProxyStatus = "resolved"
	// Error is a ProxyStatus of type error.
	Error ProxyStatus = "error"
)

var ErrInvalidProxyStatus = fmt.Errorf("not a valid ProxyStatus, try [%s]", strings.Join(_ProxyStatusNames, ", "))

var _ProxyStatusNames = []string{
	string(New),
	string(Resolved),
	string(Error),
}

// ProxyStatusNames returns a list of possible string values of ProxyStatus.
func ProxyStatusNames() []string {
	tmp := make([]string, len(_ProxyStatusNames))
	copy(tmp, _ProxyStatusNames)
	return tmp
}

// ProxyStatusValues returns a list of the values for ProxyStatus
func ProxyStatusValues() []ProxyStatus {
	return []ProxyStatus{
		New,
		Resolved,
		Error,
	}
}

// String implements the Stringer interface.
func (x ProxyStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ProxyStatus) IsValid() bool {
	_, err := ParseProxyStatus(string(x))
	return err == nil
}

var _ProxyStatusValue = map[string]ProxyStatus{
	"new":      New,
	"resolved": Resolved,
	"error":    Error,
}

// ParseProxyStatus attempts to convert a string to a ProxyStatus.
func ParseProxyStatus(name string) (ProxyStatus, error) {
	if x, ok := _ProxyStatusValue[name]; ok {
		return x, nil
	}
	return ProxyStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidProxyStatus)
}

// MarshalText implements the text marshaller method.
func (x ProxyStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ProxyStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseProxyStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var errProxyStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *ProxyStatus) Scan(value interface{}) (err error) {
	if value == nil {
		*x = ProxyStatus("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseProxyStatus(v)
	case []byte:
		*x, err = ParseProxyStatus(string(v))
	case ProxyStatus:
		*x = v
	case *ProxyStatus:
		if v == nil {
			return errProxyStatusNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errProxyStatusNilPtr
		}
		*x, err = ParseProxyStatus(*v)
	default:
		return errors.New("invalid type for ProxyStatus")
	}

	return
}

// Value implements the driver Valuer interface.
func (x ProxyStatus) Value() (driver.Value, error) {
	return x.String(), nil
}
