// Code generated by go-enum DO NOT EDIT.
// Version: 0.5.7
// Revision: bf63e108589bbd2327b13ec2c5da532aad234029
// Build Date: 2023-07-25T23:27:55Z
// Built By: goreleaser

package types

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// ERC20 is a TokenType of type ERC20.
	ERC20 TokenType = "ERC20"
	// ERC721 is a TokenType of type ERC721.
	ERC721 TokenType = "ERC721"
	// ERC1155 is a TokenType of type ERC1155.
	ERC1155 TokenType = "ERC1155"
)

var ErrInvalidTokenType = fmt.Errorf("not a valid TokenType, try [%s]", strings.Join(_TokenTypeNames, ", "))

var _TokenTypeNames = []string{
	string(ERC20),
	string(ERC721),
	string(ERC1155),
}

// TokenTypeNames returns a list of possible string values of TokenType.
func TokenTypeNames() []string {
	tmp := make([]string, len(_TokenTypeNames))
	copy(tmp, _TokenTypeNames)
	return tmp
}

// TokenTypeValues returns a list of the values for TokenType
func TokenTypeValues() []TokenType {
	return []TokenType{
		ERC20,
		ERC721,
		ERC1155,
	}
}

// String implements the Stringer interface.
func (x TokenType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TokenType) IsValid() bool {
	_, err := ParseTokenType(string(x))
	return err == nil
}

var _TokenTypeValue = map[string]TokenType{
	"ERC20":   ERC20,
	"ERC721":  ERC721,
	"ERC1155": ERC1155,
}

// ParseTokenType attempts to convert a string to a TokenType.
func ParseTokenType(name string) (TokenType, error) {
	if x, ok := _TokenTypeValue[name]; ok {
		return x, nil
	}
	return TokenType(""), fmt.Errorf("%s is %w", name, ErrInvalidTokenType)
}

// MarshalText implements the text marshaller method.
func (x TokenType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *TokenType) UnmarshalText(text []byte) error {
	tmp, err := ParseTokenType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var errTokenTypeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *TokenType) Scan(value interface{}) (err error) {
	if value == nil {
		*x = TokenType("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseTokenType(v)
	case []byte:
		*x, err = ParseTokenType(string(v))
	case TokenType:
		*x = v
	case *TokenType:
		if v == nil {
			return errTokenTypeNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errTokenTypeNilPtr
		}
		*x, err = ParseTokenType(*v)
	default:
		return errors.New("invalid type for TokenType")
	}

	return
}

// Value implements the driver Valuer interface.
func (x TokenType) Value() (driver.Value, error) {
	return x.String(), nil
}
