// Code generated by go-enum DO NOT EDIT.
// Version: 0.5.7
// Revision: bf63e108589bbd2327b13ec2c5da532aad234029
// Build Date: 2023-07-25T23:27:55Z
// Built By: goreleaser

package types

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// Call is a TraceType of type call.
	Call TraceType = "call"
	// Delegatecall is a TraceType of type delegatecall.
	Delegatecall TraceType = "delegatecall"
	// Staticcall is a TraceType of type staticcall.
	Staticcall TraceType = "staticcall"
	// Create is a TraceType of type create.
	Create TraceType = "create"
	// Create2 is a TraceType of type create2.
	Create2 TraceType = "create2"
	// Selfdestruct is a TraceType of type selfdestruct.
	Selfdestruct TraceType = "selfdestruct"
	// Reward is a TraceType of type reward.
	Reward TraceType = "reward"
	// Suicide is a TraceType of type suicide.
	Suicide TraceType = "suicide"
)

var ErrInvalidTraceType = fmt.Errorf("not a valid TraceType, try [%s]", strings.Join(_TraceTypeNames, ", "))

var _TraceTypeNames = []string{
	string(Call),
	string(Delegatecall),
	string(Staticcall),
	string(Create),
	string(Create2),
	string(Selfdestruct),
	string(Reward),
	string(Suicide),
}

// TraceTypeNames returns a list of possible string values of TraceType.
func TraceTypeNames() []string {
	tmp := make([]string, len(_TraceTypeNames))
	copy(tmp, _TraceTypeNames)
	return tmp
}

// TraceTypeValues returns a list of the values for TraceType
func TraceTypeValues() []TraceType {
	return []TraceType{
		Call,
		Delegatecall,
		Staticcall,
		Create,
		Create2,
		Selfdestruct,
		Reward,
		Suicide,
	}
}

// String implements the Stringer interface.
func (x TraceType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TraceType) IsValid() bool {
	_, err := ParseTraceType(string(x))
	return err == nil
}

var _TraceTypeValue = map[string]TraceType{
	"call":         Call,
	"delegatecall": Delegatecall,
	"staticcall":   Staticcall,
	"create":       Create,
	"create2":      Create2,
	"selfdestruct": Selfdestruct,
	"reward":       Reward,
	"suicide":      Suicide,
}

// ParseTraceType attempts to convert a string to a TraceType.
func ParseTraceType(name string) (TraceType, error) {
	if x, ok := _TraceTypeValue[name]; ok {
		return x, nil
	}
	return TraceType(""), fmt.Errorf("%s is %w", name, ErrInvalidTraceType)
}

// MarshalText implements the text marshaller method.
func (x TraceType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *TraceType) UnmarshalText(text []byte) error {
	tmp, err := ParseTraceType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var errTraceTypeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *TraceType) Scan(value interface{}) (err error) {
	if value == nil {
		*x = TraceType("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseTraceType(v)
	case []byte:
		*x, err = ParseTraceType(string(v))
	case TraceType:
		*x = v
	case *TraceType:
		if v == nil {
			return errTraceTypeNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errTraceTypeNilPtr
		}
		*x, err = ParseTraceType(*v)
	default:
		return errors.New("invalid type for TraceType")
	}

	return
}

// Value implements the driver Valuer interface.
func (x TraceType) Value() (driver.Value, error) {
	return x.String(), nil
}
