// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// Burn is a TransferType of type burn.
	Burn TransferType = "burn"
	// Mint is a TransferType of type mint.
	Mint TransferType = "mint"
	// Transfer is a TransferType of type transfer.
	Transfer TransferType = "transfer"
	// Unknown is a TransferType of type unknown.
	Unknown TransferType = "unknown"
)

var ErrInvalidTransferType = fmt.Errorf("not a valid TransferType, try [%s]", strings.Join(_TransferTypeNames, ", "))

var _TransferTypeNames = []string{
	string(Burn),
	string(Mint),
	string(Transfer),
	string(Unknown),
}

// TransferTypeNames returns a list of possible string values of TransferType.
func TransferTypeNames() []string {
	tmp := make([]string, len(_TransferTypeNames))
	copy(tmp, _TransferTypeNames)
	return tmp
}

// TransferTypeValues returns a list of the values for TransferType
func TransferTypeValues() []TransferType {
	return []TransferType{
		Burn,
		Mint,
		Transfer,
		Unknown,
	}
}

// String implements the Stringer interface.
func (x TransferType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TransferType) IsValid() bool {
	_, err := ParseTransferType(string(x))
	return err == nil
}

var _TransferTypeValue = map[string]TransferType{
	"burn":     Burn,
	"mint":     Mint,
	"transfer": Transfer,
	"unknown":  Unknown,
}

// ParseTransferType attempts to convert a string to a TransferType.
func ParseTransferType(name string) (TransferType, error) {
	if x, ok := _TransferTypeValue[name]; ok {
		return x, nil
	}
	return TransferType(""), fmt.Errorf("%s is %w", name, ErrInvalidTransferType)
}

// MarshalText implements the text marshaller method.
func (x TransferType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *TransferType) UnmarshalText(text []byte) error {
	tmp, err := ParseTransferType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *TransferType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errTransferTypeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *TransferType) Scan(value interface{}) (err error) {
	if value == nil {
		*x = TransferType("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseTransferType(v)
	case []byte:
		*x, err = ParseTransferType(string(v))
	case TransferType:
		*x = v
	case *TransferType:
		if v == nil {
			return errTransferTypeNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errTransferTypeNilPtr
		}
		*x, err = ParseTransferType(*v)
	default:
		return errors.New("invalid type for TransferType")
	}

	return
}

// Value implements the driver Valuer interface.
func (x TransferType) Value() (driver.Value, error) {
	return x.String(), nil
}
