// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// TxStatusSuccess is a TxStatus of type TxStatusSuccess.
	TxStatusSuccess TxStatus = "TxStatusSuccess"
	// TxStatusRevert is a TxStatus of type TxStatusRevert.
	TxStatusRevert TxStatus = "TxStatusRevert"
)

var ErrInvalidTxStatus = fmt.Errorf("not a valid TxStatus, try [%s]", strings.Join(_TxStatusNames, ", "))

var _TxStatusNames = []string{
	string(TxStatusSuccess),
	string(TxStatusRevert),
}

// TxStatusNames returns a list of possible string values of TxStatus.
func TxStatusNames() []string {
	tmp := make([]string, len(_TxStatusNames))
	copy(tmp, _TxStatusNames)
	return tmp
}

// TxStatusValues returns a list of the values for TxStatus
func TxStatusValues() []TxStatus {
	return []TxStatus{
		TxStatusSuccess,
		TxStatusRevert,
	}
}

// String implements the Stringer interface.
func (x TxStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TxStatus) IsValid() bool {
	_, err := ParseTxStatus(string(x))
	return err == nil
}

var _TxStatusValue = map[string]TxStatus{
	"TxStatusSuccess": TxStatusSuccess,
	"TxStatusRevert":  TxStatusRevert,
}

// ParseTxStatus attempts to convert a string to a TxStatus.
func ParseTxStatus(name string) (TxStatus, error) {
	if x, ok := _TxStatusValue[name]; ok {
		return x, nil
	}
	return TxStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidTxStatus)
}

// MarshalText implements the text marshaller method.
func (x TxStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *TxStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseTxStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var errTxStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *TxStatus) Scan(value interface{}) (err error) {
	if value == nil {
		*x = TxStatus("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseTxStatus(v)
	case []byte:
		*x, err = ParseTxStatus(string(v))
	case TxStatus:
		*x = v
	case *TxStatus:
		if v == nil {
			return errTxStatusNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errTxStatusNilPtr
		}
		*x, err = ParseTxStatus(*v)
	default:
		return errors.New("invalid type for TxStatus")
	}

	return
}

// Value implements the driver Valuer interface.
func (x TxStatus) Value() (driver.Value, error) {
	return x.String(), nil
}
