// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// TxTypeUnknown is a TxType of type TxTypeUnknown.
	TxTypeUnknown TxType = "TxTypeUnknown"
	// TxTypeLegacy is a TxType of type TxTypeLegacy.
	TxTypeLegacy TxType = "TxTypeLegacy"
	// TxTypeDynamicFee is a TxType of type TxTypeDynamicFee.
	TxTypeDynamicFee TxType = "TxTypeDynamicFee"
)

var ErrInvalidTxType = fmt.Errorf("not a valid TxType, try [%s]", strings.Join(_TxTypeNames, ", "))

var _TxTypeNames = []string{
	string(TxTypeUnknown),
	string(TxTypeLegacy),
	string(TxTypeDynamicFee),
}

// TxTypeNames returns a list of possible string values of TxType.
func TxTypeNames() []string {
	tmp := make([]string, len(_TxTypeNames))
	copy(tmp, _TxTypeNames)
	return tmp
}

// TxTypeValues returns a list of the values for TxType
func TxTypeValues() []TxType {
	return []TxType{
		TxTypeUnknown,
		TxTypeLegacy,
		TxTypeDynamicFee,
	}
}

// String implements the Stringer interface.
func (x TxType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TxType) IsValid() bool {
	_, err := ParseTxType(string(x))
	return err == nil
}

var _TxTypeValue = map[string]TxType{
	"TxTypeUnknown":    TxTypeUnknown,
	"TxTypeLegacy":     TxTypeLegacy,
	"TxTypeDynamicFee": TxTypeDynamicFee,
}

// ParseTxType attempts to convert a string to a TxType.
func ParseTxType(name string) (TxType, error) {
	if x, ok := _TxTypeValue[name]; ok {
		return x, nil
	}
	return TxType(""), fmt.Errorf("%s is %w", name, ErrInvalidTxType)
}

// MarshalText implements the text marshaller method.
func (x TxType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *TxType) UnmarshalText(text []byte) error {
	tmp, err := ParseTxType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var errTxTypeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *TxType) Scan(value interface{}) (err error) {
	if value == nil {
		*x = TxType("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseTxType(v)
	case []byte:
		*x, err = ParseTxType(string(v))
	case TxType:
		*x = v
	case *TxType:
		if v == nil {
			return errTxTypeNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errTxTypeNilPtr
		}
		*x, err = ParseTxType(*v)
	default:
		return errors.New("invalid type for TxType")
	}

	return
}

// Value implements the driver Valuer interface.
func (x TxType) Value() (driver.Value, error) {
	return x.String(), nil
}
