// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// VerificationStatusNew is a VerificationTaskStatus of type VerificationStatusNew.
	VerificationStatusNew VerificationTaskStatus = "VerificationStatusNew"
	// VerificationStatusPending is a VerificationTaskStatus of type VerificationStatusPending.
	VerificationStatusPending VerificationTaskStatus = "VerificationStatusPending"
	// VerificationStatusFailed is a VerificationTaskStatus of type VerificationStatusFailed.
	VerificationStatusFailed VerificationTaskStatus = "VerificationStatusFailed"
	// VerificationStatusSuccess is a VerificationTaskStatus of type VerificationStatusSuccess.
	VerificationStatusSuccess VerificationTaskStatus = "VerificationStatusSuccess"
)

var ErrInvalidVerificationTaskStatus = fmt.Errorf("not a valid VerificationTaskStatus, try [%s]", strings.Join(_VerificationTaskStatusNames, ", "))

var _VerificationTaskStatusNames = []string{
	string(VerificationStatusNew),
	string(VerificationStatusPending),
	string(VerificationStatusFailed),
	string(VerificationStatusSuccess),
}

// VerificationTaskStatusNames returns a list of possible string values of VerificationTaskStatus.
func VerificationTaskStatusNames() []string {
	tmp := make([]string, len(_VerificationTaskStatusNames))
	copy(tmp, _VerificationTaskStatusNames)
	return tmp
}

// VerificationTaskStatusValues returns a list of the values for VerificationTaskStatus
func VerificationTaskStatusValues() []VerificationTaskStatus {
	return []VerificationTaskStatus{
		VerificationStatusNew,
		VerificationStatusPending,
		VerificationStatusFailed,
		VerificationStatusSuccess,
	}
}

// String implements the Stringer interface.
func (x VerificationTaskStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x VerificationTaskStatus) IsValid() bool {
	_, err := ParseVerificationTaskStatus(string(x))
	return err == nil
}

var _VerificationTaskStatusValue = map[string]VerificationTaskStatus{
	"VerificationStatusNew":     VerificationStatusNew,
	"VerificationStatusPending": VerificationStatusPending,
	"VerificationStatusFailed":  VerificationStatusFailed,
	"VerificationStatusSuccess": VerificationStatusSuccess,
}

// ParseVerificationTaskStatus attempts to convert a string to a VerificationTaskStatus.
func ParseVerificationTaskStatus(name string) (VerificationTaskStatus, error) {
	if x, ok := _VerificationTaskStatusValue[name]; ok {
		return x, nil
	}
	return VerificationTaskStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidVerificationTaskStatus)
}

// MarshalText implements the text marshaller method.
func (x VerificationTaskStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *VerificationTaskStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseVerificationTaskStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var errVerificationTaskStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *VerificationTaskStatus) Scan(value interface{}) (err error) {
	if value == nil {
		*x = VerificationTaskStatus("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseVerificationTaskStatus(v)
	case []byte:
		*x, err = ParseVerificationTaskStatus(string(v))
	case VerificationTaskStatus:
		*x = v
	case *VerificationTaskStatus:
		if v == nil {
			return errVerificationTaskStatusNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errVerificationTaskStatusNilPtr
		}
		*x, err = ParseVerificationTaskStatus(*v)
	default:
		return errors.New("invalid type for VerificationTaskStatus")
	}

	return
}

// Value implements the driver Valuer interface.
func (x VerificationTaskStatus) Value() (driver.Value, error) {
	return x.String(), nil
}
