// Code generated by MockGen. DO NOT EDIT.
// Source: beacon_withdrawal.go
//
// Generated by this command:
//
//	mockgen -source=beacon_withdrawal.go -destination=mock/beacon_withdrawal.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	storage "github.com/baking-bad/noble-indexer/internal/storage"
	storage0 "github.com/dipdup-net/indexer-sdk/pkg/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockIBeaconWithdrawal is a mock of IBeaconWithdrawal interface.
type MockIBeaconWithdrawal struct {
	ctrl     *gomock.Controller
	recorder *MockIBeaconWithdrawalMockRecorder
	isgomock struct{}
}

// MockIBeaconWithdrawalMockRecorder is the mock recorder for MockIBeaconWithdrawal.
type MockIBeaconWithdrawalMockRecorder struct {
	mock *MockIBeaconWithdrawal
}

// NewMockIBeaconWithdrawal creates a new mock instance.
func NewMockIBeaconWithdrawal(ctrl *gomock.Controller) *MockIBeaconWithdrawal {
	mock := &MockIBeaconWithdrawal{ctrl: ctrl}
	mock.recorder = &MockIBeaconWithdrawalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBeaconWithdrawal) EXPECT() *MockIBeaconWithdrawalMockRecorder {
	return m.recorder
}

// CursorList mocks base method.
func (m *MockIBeaconWithdrawal) CursorList(ctx context.Context, id, limit uint64, order storage0.SortOrder, cmp storage0.Comparator) ([]*storage.BeaconWithdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CursorList", ctx, id, limit, order, cmp)
	ret0, _ := ret[0].([]*storage.BeaconWithdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CursorList indicates an expected call of CursorList.
func (mr *MockIBeaconWithdrawalMockRecorder) CursorList(ctx, id, limit, order, cmp any) *MockIBeaconWithdrawalCursorListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CursorList", reflect.TypeOf((*MockIBeaconWithdrawal)(nil).CursorList), ctx, id, limit, order, cmp)
	return &MockIBeaconWithdrawalCursorListCall{Call: call}
}

// MockIBeaconWithdrawalCursorListCall wrap *gomock.Call
type MockIBeaconWithdrawalCursorListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIBeaconWithdrawalCursorListCall) Return(arg0 []*storage.BeaconWithdrawal, arg1 error) *MockIBeaconWithdrawalCursorListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIBeaconWithdrawalCursorListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.BeaconWithdrawal, error)) *MockIBeaconWithdrawalCursorListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIBeaconWithdrawalCursorListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.BeaconWithdrawal, error)) *MockIBeaconWithdrawalCursorListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Filter mocks base method.
func (m *MockIBeaconWithdrawal) Filter(ctx context.Context, filter storage.BeaconWithdrawalListFilter) ([]*storage.BeaconWithdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, filter)
	ret0, _ := ret[0].([]*storage.BeaconWithdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *MockIBeaconWithdrawalMockRecorder) Filter(ctx, filter any) *MockIBeaconWithdrawalFilterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*MockIBeaconWithdrawal)(nil).Filter), ctx, filter)
	return &MockIBeaconWithdrawalFilterCall{Call: call}
}

// MockIBeaconWithdrawalFilterCall wrap *gomock.Call
type MockIBeaconWithdrawalFilterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIBeaconWithdrawalFilterCall) Return(beaconWithdrawals []*storage.BeaconWithdrawal, err error) *MockIBeaconWithdrawalFilterCall {
	c.Call = c.Call.Return(beaconWithdrawals, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIBeaconWithdrawalFilterCall) Do(f func(context.Context, storage.BeaconWithdrawalListFilter) ([]*storage.BeaconWithdrawal, error)) *MockIBeaconWithdrawalFilterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIBeaconWithdrawalFilterCall) DoAndReturn(f func(context.Context, storage.BeaconWithdrawalListFilter) ([]*storage.BeaconWithdrawal, error)) *MockIBeaconWithdrawalFilterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockIBeaconWithdrawal) GetByID(ctx context.Context, id uint64) (*storage.BeaconWithdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*storage.BeaconWithdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIBeaconWithdrawalMockRecorder) GetByID(ctx, id any) *MockIBeaconWithdrawalGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIBeaconWithdrawal)(nil).GetByID), ctx, id)
	return &MockIBeaconWithdrawalGetByIDCall{Call: call}
}

// MockIBeaconWithdrawalGetByIDCall wrap *gomock.Call
type MockIBeaconWithdrawalGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIBeaconWithdrawalGetByIDCall) Return(arg0 *storage.BeaconWithdrawal, arg1 error) *MockIBeaconWithdrawalGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIBeaconWithdrawalGetByIDCall) Do(f func(context.Context, uint64) (*storage.BeaconWithdrawal, error)) *MockIBeaconWithdrawalGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIBeaconWithdrawalGetByIDCall) DoAndReturn(f func(context.Context, uint64) (*storage.BeaconWithdrawal, error)) *MockIBeaconWithdrawalGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsNoRows mocks base method.
func (m *MockIBeaconWithdrawal) IsNoRows(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNoRows", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNoRows indicates an expected call of IsNoRows.
func (mr *MockIBeaconWithdrawalMockRecorder) IsNoRows(err any) *MockIBeaconWithdrawalIsNoRowsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNoRows", reflect.TypeOf((*MockIBeaconWithdrawal)(nil).IsNoRows), err)
	return &MockIBeaconWithdrawalIsNoRowsCall{Call: call}
}

// MockIBeaconWithdrawalIsNoRowsCall wrap *gomock.Call
type MockIBeaconWithdrawalIsNoRowsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIBeaconWithdrawalIsNoRowsCall) Return(arg0 bool) *MockIBeaconWithdrawalIsNoRowsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIBeaconWithdrawalIsNoRowsCall) Do(f func(error) bool) *MockIBeaconWithdrawalIsNoRowsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIBeaconWithdrawalIsNoRowsCall) DoAndReturn(f func(error) bool) *MockIBeaconWithdrawalIsNoRowsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LastID mocks base method.
func (m *MockIBeaconWithdrawal) LastID(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastID", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastID indicates an expected call of LastID.
func (mr *MockIBeaconWithdrawalMockRecorder) LastID(ctx any) *MockIBeaconWithdrawalLastIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastID", reflect.TypeOf((*MockIBeaconWithdrawal)(nil).LastID), ctx)
	return &MockIBeaconWithdrawalLastIDCall{Call: call}
}

// MockIBeaconWithdrawalLastIDCall wrap *gomock.Call
type MockIBeaconWithdrawalLastIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIBeaconWithdrawalLastIDCall) Return(arg0 uint64, arg1 error) *MockIBeaconWithdrawalLastIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIBeaconWithdrawalLastIDCall) Do(f func(context.Context) (uint64, error)) *MockIBeaconWithdrawalLastIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIBeaconWithdrawalLastIDCall) DoAndReturn(f func(context.Context) (uint64, error)) *MockIBeaconWithdrawalLastIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockIBeaconWithdrawal) List(ctx context.Context, limit, offset uint64, order storage0.SortOrder) ([]*storage.BeaconWithdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset, order)
	ret0, _ := ret[0].([]*storage.BeaconWithdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIBeaconWithdrawalMockRecorder) List(ctx, limit, offset, order any) *MockIBeaconWithdrawalListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIBeaconWithdrawal)(nil).List), ctx, limit, offset, order)
	return &MockIBeaconWithdrawalListCall{Call: call}
}

// MockIBeaconWithdrawalListCall wrap *gomock.Call
type MockIBeaconWithdrawalListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIBeaconWithdrawalListCall) Return(arg0 []*storage.BeaconWithdrawal, arg1 error) *MockIBeaconWithdrawalListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIBeaconWithdrawalListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.BeaconWithdrawal, error)) *MockIBeaconWithdrawalListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIBeaconWithdrawalListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.BeaconWithdrawal, error)) *MockIBeaconWithdrawalListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m_2 *MockIBeaconWithdrawal) Save(ctx context.Context, m *storage.BeaconWithdrawal) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockIBeaconWithdrawalMockRecorder) Save(ctx, m any) *MockIBeaconWithdrawalSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIBeaconWithdrawal)(nil).Save), ctx, m)
	return &MockIBeaconWithdrawalSaveCall{Call: call}
}

// MockIBeaconWithdrawalSaveCall wrap *gomock.Call
type MockIBeaconWithdrawalSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIBeaconWithdrawalSaveCall) Return(arg0 error) *MockIBeaconWithdrawalSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIBeaconWithdrawalSaveCall) Do(f func(context.Context, *storage.BeaconWithdrawal) error) *MockIBeaconWithdrawalSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIBeaconWithdrawalSaveCall) DoAndReturn(f func(context.Context, *storage.BeaconWithdrawal) error) *MockIBeaconWithdrawalSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m_2 *MockIBeaconWithdrawal) Update(ctx context.Context, m *storage.BeaconWithdrawal) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIBeaconWithdrawalMockRecorder) Update(ctx, m any) *MockIBeaconWithdrawalUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIBeaconWithdrawal)(nil).Update), ctx, m)
	return &MockIBeaconWithdrawalUpdateCall{Call: call}
}

// MockIBeaconWithdrawalUpdateCall wrap *gomock.Call
type MockIBeaconWithdrawalUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIBeaconWithdrawalUpdateCall) Return(arg0 error) *MockIBeaconWithdrawalUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIBeaconWithdrawalUpdateCall) Do(f func(context.Context, *storage.BeaconWithdrawal) error) *MockIBeaconWithdrawalUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIBeaconWithdrawalUpdateCall) DoAndReturn(f func(context.Context, *storage.BeaconWithdrawal) error) *MockIBeaconWithdrawalUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
