// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock/contract.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	storage "github.com/baking-bad/noble-indexer/internal/storage"
	types "github.com/baking-bad/noble-indexer/pkg/types"
	storage0 "github.com/dipdup-net/indexer-sdk/pkg/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockIContract is a mock of IContract interface.
type MockIContract struct {
	ctrl     *gomock.Controller
	recorder *MockIContractMockRecorder
	isgomock struct{}
}

// MockIContractMockRecorder is the mock recorder for MockIContract.
type MockIContractMockRecorder struct {
	mock *MockIContract
}

// NewMockIContract creates a new mock instance.
func NewMockIContract(ctrl *gomock.Controller) *MockIContract {
	mock := &MockIContract{ctrl: ctrl}
	mock.recorder = &MockIContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContract) EXPECT() *MockIContractMockRecorder {
	return m.recorder
}

// ByHash mocks base method.
func (m *MockIContract) ByHash(ctx context.Context, hash types.Hex) (storage.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByHash", ctx, hash)
	ret0, _ := ret[0].(storage.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByHash indicates an expected call of ByHash.
func (mr *MockIContractMockRecorder) ByHash(ctx, hash any) *MockIContractByHashCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByHash", reflect.TypeOf((*MockIContract)(nil).ByHash), ctx, hash)
	return &MockIContractByHashCall{Call: call}
}

// MockIContractByHashCall wrap *gomock.Call
type MockIContractByHashCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIContractByHashCall) Return(arg0 storage.Contract, arg1 error) *MockIContractByHashCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIContractByHashCall) Do(f func(context.Context, types.Hex) (storage.Contract, error)) *MockIContractByHashCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIContractByHashCall) DoAndReturn(f func(context.Context, types.Hex) (storage.Contract, error)) *MockIContractByHashCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ByTxId mocks base method.
func (m *MockIContract) ByTxId(ctx context.Context, id uint64) (storage.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByTxId", ctx, id)
	ret0, _ := ret[0].(storage.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByTxId indicates an expected call of ByTxId.
func (mr *MockIContractMockRecorder) ByTxId(ctx, id any) *MockIContractByTxIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByTxId", reflect.TypeOf((*MockIContract)(nil).ByTxId), ctx, id)
	return &MockIContractByTxIdCall{Call: call}
}

// MockIContractByTxIdCall wrap *gomock.Call
type MockIContractByTxIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIContractByTxIdCall) Return(arg0 storage.Contract, arg1 error) *MockIContractByTxIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIContractByTxIdCall) Do(f func(context.Context, uint64) (storage.Contract, error)) *MockIContractByTxIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIContractByTxIdCall) DoAndReturn(f func(context.Context, uint64) (storage.Contract, error)) *MockIContractByTxIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CursorList mocks base method.
func (m *MockIContract) CursorList(ctx context.Context, id, limit uint64, order storage0.SortOrder, cmp storage0.Comparator) ([]*storage.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CursorList", ctx, id, limit, order, cmp)
	ret0, _ := ret[0].([]*storage.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CursorList indicates an expected call of CursorList.
func (mr *MockIContractMockRecorder) CursorList(ctx, id, limit, order, cmp any) *MockIContractCursorListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CursorList", reflect.TypeOf((*MockIContract)(nil).CursorList), ctx, id, limit, order, cmp)
	return &MockIContractCursorListCall{Call: call}
}

// MockIContractCursorListCall wrap *gomock.Call
type MockIContractCursorListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIContractCursorListCall) Return(arg0 []*storage.Contract, arg1 error) *MockIContractCursorListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIContractCursorListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.Contract, error)) *MockIContractCursorListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIContractCursorListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.Contract, error)) *MockIContractCursorListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockIContract) GetByID(ctx context.Context, id uint64) (*storage.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*storage.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIContractMockRecorder) GetByID(ctx, id any) *MockIContractGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIContract)(nil).GetByID), ctx, id)
	return &MockIContractGetByIDCall{Call: call}
}

// MockIContractGetByIDCall wrap *gomock.Call
type MockIContractGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIContractGetByIDCall) Return(arg0 *storage.Contract, arg1 error) *MockIContractGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIContractGetByIDCall) Do(f func(context.Context, uint64) (*storage.Contract, error)) *MockIContractGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIContractGetByIDCall) DoAndReturn(f func(context.Context, uint64) (*storage.Contract, error)) *MockIContractGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsNoRows mocks base method.
func (m *MockIContract) IsNoRows(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNoRows", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNoRows indicates an expected call of IsNoRows.
func (mr *MockIContractMockRecorder) IsNoRows(err any) *MockIContractIsNoRowsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNoRows", reflect.TypeOf((*MockIContract)(nil).IsNoRows), err)
	return &MockIContractIsNoRowsCall{Call: call}
}

// MockIContractIsNoRowsCall wrap *gomock.Call
type MockIContractIsNoRowsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIContractIsNoRowsCall) Return(arg0 bool) *MockIContractIsNoRowsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIContractIsNoRowsCall) Do(f func(error) bool) *MockIContractIsNoRowsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIContractIsNoRowsCall) DoAndReturn(f func(error) bool) *MockIContractIsNoRowsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LastID mocks base method.
func (m *MockIContract) LastID(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastID", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastID indicates an expected call of LastID.
func (mr *MockIContractMockRecorder) LastID(ctx any) *MockIContractLastIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastID", reflect.TypeOf((*MockIContract)(nil).LastID), ctx)
	return &MockIContractLastIDCall{Call: call}
}

// MockIContractLastIDCall wrap *gomock.Call
type MockIContractLastIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIContractLastIDCall) Return(arg0 uint64, arg1 error) *MockIContractLastIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIContractLastIDCall) Do(f func(context.Context) (uint64, error)) *MockIContractLastIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIContractLastIDCall) DoAndReturn(f func(context.Context) (uint64, error)) *MockIContractLastIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockIContract) List(ctx context.Context, limit, offset uint64, order storage0.SortOrder) ([]*storage.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset, order)
	ret0, _ := ret[0].([]*storage.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIContractMockRecorder) List(ctx, limit, offset, order any) *MockIContractListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIContract)(nil).List), ctx, limit, offset, order)
	return &MockIContractListCall{Call: call}
}

// MockIContractListCall wrap *gomock.Call
type MockIContractListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIContractListCall) Return(arg0 []*storage.Contract, arg1 error) *MockIContractListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIContractListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.Contract, error)) *MockIContractListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIContractListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.Contract, error)) *MockIContractListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListWithTx mocks base method.
func (m *MockIContract) ListWithTx(ctx context.Context, filters storage.ContractListFilter) ([]storage.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithTx", ctx, filters)
	ret0, _ := ret[0].([]storage.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithTx indicates an expected call of ListWithTx.
func (mr *MockIContractMockRecorder) ListWithTx(ctx, filters any) *MockIContractListWithTxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithTx", reflect.TypeOf((*MockIContract)(nil).ListWithTx), ctx, filters)
	return &MockIContractListWithTxCall{Call: call}
}

// MockIContractListWithTxCall wrap *gomock.Call
type MockIContractListWithTxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIContractListWithTxCall) Return(arg0 []storage.Contract, arg1 error) *MockIContractListWithTxCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIContractListWithTxCall) Do(f func(context.Context, storage.ContractListFilter) ([]storage.Contract, error)) *MockIContractListWithTxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIContractListWithTxCall) DoAndReturn(f func(context.Context, storage.ContractListFilter) ([]storage.Contract, error)) *MockIContractListWithTxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PendingMetadata mocks base method.
func (m *MockIContract) PendingMetadata(ctx context.Context, delay time.Duration, limit int) ([]*storage.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingMetadata", ctx, delay, limit)
	ret0, _ := ret[0].([]*storage.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PendingMetadata indicates an expected call of PendingMetadata.
func (mr *MockIContractMockRecorder) PendingMetadata(ctx, delay, limit any) *MockIContractPendingMetadataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingMetadata", reflect.TypeOf((*MockIContract)(nil).PendingMetadata), ctx, delay, limit)
	return &MockIContractPendingMetadataCall{Call: call}
}

// MockIContractPendingMetadataCall wrap *gomock.Call
type MockIContractPendingMetadataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIContractPendingMetadataCall) Return(arg0 []*storage.Contract, arg1 error) *MockIContractPendingMetadataCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIContractPendingMetadataCall) Do(f func(context.Context, time.Duration, int) ([]*storage.Contract, error)) *MockIContractPendingMetadataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIContractPendingMetadataCall) DoAndReturn(f func(context.Context, time.Duration, int) ([]*storage.Contract, error)) *MockIContractPendingMetadataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m_2 *MockIContract) Save(ctx context.Context, m *storage.Contract) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockIContractMockRecorder) Save(ctx, m any) *MockIContractSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIContract)(nil).Save), ctx, m)
	return &MockIContractSaveCall{Call: call}
}

// MockIContractSaveCall wrap *gomock.Call
type MockIContractSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIContractSaveCall) Return(arg0 error) *MockIContractSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIContractSaveCall) Do(f func(context.Context, *storage.Contract) error) *MockIContractSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIContractSaveCall) DoAndReturn(f func(context.Context, *storage.Contract) error) *MockIContractSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m_2 *MockIContract) Update(ctx context.Context, m *storage.Contract) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIContractMockRecorder) Update(ctx, m any) *MockIContractUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIContract)(nil).Update), ctx, m)
	return &MockIContractUpdateCall{Call: call}
}

// MockIContractUpdateCall wrap *gomock.Call
type MockIContractUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIContractUpdateCall) Return(arg0 error) *MockIContractUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIContractUpdateCall) Do(f func(context.Context, *storage.Contract) error) *MockIContractUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIContractUpdateCall) DoAndReturn(f func(context.Context, *storage.Contract) error) *MockIContractUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
