// Code generated by MockGen. DO NOT EDIT.
// Source: erc4337_user_ops.go
//
// Generated by this command:
//
//	mockgen -source=erc4337_user_ops.go -destination=mock/erc4337_user_ops.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	storage "github.com/baking-bad/noble-indexer/internal/storage"
	storage0 "github.com/dipdup-net/indexer-sdk/pkg/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockIERC4337UserOps is a mock of IERC4337UserOps interface.
type MockIERC4337UserOps struct {
	ctrl     *gomock.Controller
	recorder *MockIERC4337UserOpsMockRecorder
	isgomock struct{}
}

// MockIERC4337UserOpsMockRecorder is the mock recorder for MockIERC4337UserOps.
type MockIERC4337UserOpsMockRecorder struct {
	mock *MockIERC4337UserOps
}

// NewMockIERC4337UserOps creates a new mock instance.
func NewMockIERC4337UserOps(ctrl *gomock.Controller) *MockIERC4337UserOps {
	mock := &MockIERC4337UserOps{ctrl: ctrl}
	mock.recorder = &MockIERC4337UserOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIERC4337UserOps) EXPECT() *MockIERC4337UserOpsMockRecorder {
	return m.recorder
}

// CursorList mocks base method.
func (m *MockIERC4337UserOps) CursorList(ctx context.Context, id, limit uint64, order storage0.SortOrder, cmp storage0.Comparator) ([]*storage.ERC4337UserOp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CursorList", ctx, id, limit, order, cmp)
	ret0, _ := ret[0].([]*storage.ERC4337UserOp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CursorList indicates an expected call of CursorList.
func (mr *MockIERC4337UserOpsMockRecorder) CursorList(ctx, id, limit, order, cmp any) *MockIERC4337UserOpsCursorListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CursorList", reflect.TypeOf((*MockIERC4337UserOps)(nil).CursorList), ctx, id, limit, order, cmp)
	return &MockIERC4337UserOpsCursorListCall{Call: call}
}

// MockIERC4337UserOpsCursorListCall wrap *gomock.Call
type MockIERC4337UserOpsCursorListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIERC4337UserOpsCursorListCall) Return(arg0 []*storage.ERC4337UserOp, arg1 error) *MockIERC4337UserOpsCursorListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIERC4337UserOpsCursorListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.ERC4337UserOp, error)) *MockIERC4337UserOpsCursorListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIERC4337UserOpsCursorListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.ERC4337UserOp, error)) *MockIERC4337UserOpsCursorListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Filter mocks base method.
func (m *MockIERC4337UserOps) Filter(ctx context.Context, filter storage.ERC4337UserOpsListFilter) ([]storage.ERC4337UserOp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, filter)
	ret0, _ := ret[0].([]storage.ERC4337UserOp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *MockIERC4337UserOpsMockRecorder) Filter(ctx, filter any) *MockIERC4337UserOpsFilterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*MockIERC4337UserOps)(nil).Filter), ctx, filter)
	return &MockIERC4337UserOpsFilterCall{Call: call}
}

// MockIERC4337UserOpsFilterCall wrap *gomock.Call
type MockIERC4337UserOpsFilterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIERC4337UserOpsFilterCall) Return(arg0 []storage.ERC4337UserOp, arg1 error) *MockIERC4337UserOpsFilterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIERC4337UserOpsFilterCall) Do(f func(context.Context, storage.ERC4337UserOpsListFilter) ([]storage.ERC4337UserOp, error)) *MockIERC4337UserOpsFilterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIERC4337UserOpsFilterCall) DoAndReturn(f func(context.Context, storage.ERC4337UserOpsListFilter) ([]storage.ERC4337UserOp, error)) *MockIERC4337UserOpsFilterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockIERC4337UserOps) GetByID(ctx context.Context, id uint64) (*storage.ERC4337UserOp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*storage.ERC4337UserOp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIERC4337UserOpsMockRecorder) GetByID(ctx, id any) *MockIERC4337UserOpsGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIERC4337UserOps)(nil).GetByID), ctx, id)
	return &MockIERC4337UserOpsGetByIDCall{Call: call}
}

// MockIERC4337UserOpsGetByIDCall wrap *gomock.Call
type MockIERC4337UserOpsGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIERC4337UserOpsGetByIDCall) Return(arg0 *storage.ERC4337UserOp, arg1 error) *MockIERC4337UserOpsGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIERC4337UserOpsGetByIDCall) Do(f func(context.Context, uint64) (*storage.ERC4337UserOp, error)) *MockIERC4337UserOpsGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIERC4337UserOpsGetByIDCall) DoAndReturn(f func(context.Context, uint64) (*storage.ERC4337UserOp, error)) *MockIERC4337UserOpsGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsNoRows mocks base method.
func (m *MockIERC4337UserOps) IsNoRows(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNoRows", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNoRows indicates an expected call of IsNoRows.
func (mr *MockIERC4337UserOpsMockRecorder) IsNoRows(err any) *MockIERC4337UserOpsIsNoRowsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNoRows", reflect.TypeOf((*MockIERC4337UserOps)(nil).IsNoRows), err)
	return &MockIERC4337UserOpsIsNoRowsCall{Call: call}
}

// MockIERC4337UserOpsIsNoRowsCall wrap *gomock.Call
type MockIERC4337UserOpsIsNoRowsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIERC4337UserOpsIsNoRowsCall) Return(arg0 bool) *MockIERC4337UserOpsIsNoRowsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIERC4337UserOpsIsNoRowsCall) Do(f func(error) bool) *MockIERC4337UserOpsIsNoRowsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIERC4337UserOpsIsNoRowsCall) DoAndReturn(f func(error) bool) *MockIERC4337UserOpsIsNoRowsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LastID mocks base method.
func (m *MockIERC4337UserOps) LastID(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastID", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastID indicates an expected call of LastID.
func (mr *MockIERC4337UserOpsMockRecorder) LastID(ctx any) *MockIERC4337UserOpsLastIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastID", reflect.TypeOf((*MockIERC4337UserOps)(nil).LastID), ctx)
	return &MockIERC4337UserOpsLastIDCall{Call: call}
}

// MockIERC4337UserOpsLastIDCall wrap *gomock.Call
type MockIERC4337UserOpsLastIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIERC4337UserOpsLastIDCall) Return(arg0 uint64, arg1 error) *MockIERC4337UserOpsLastIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIERC4337UserOpsLastIDCall) Do(f func(context.Context) (uint64, error)) *MockIERC4337UserOpsLastIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIERC4337UserOpsLastIDCall) DoAndReturn(f func(context.Context) (uint64, error)) *MockIERC4337UserOpsLastIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockIERC4337UserOps) List(ctx context.Context, limit, offset uint64, order storage0.SortOrder) ([]*storage.ERC4337UserOp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset, order)
	ret0, _ := ret[0].([]*storage.ERC4337UserOp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIERC4337UserOpsMockRecorder) List(ctx, limit, offset, order any) *MockIERC4337UserOpsListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIERC4337UserOps)(nil).List), ctx, limit, offset, order)
	return &MockIERC4337UserOpsListCall{Call: call}
}

// MockIERC4337UserOpsListCall wrap *gomock.Call
type MockIERC4337UserOpsListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIERC4337UserOpsListCall) Return(arg0 []*storage.ERC4337UserOp, arg1 error) *MockIERC4337UserOpsListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIERC4337UserOpsListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.ERC4337UserOp, error)) *MockIERC4337UserOpsListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIERC4337UserOpsListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.ERC4337UserOp, error)) *MockIERC4337UserOpsListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m_2 *MockIERC4337UserOps) Save(ctx context.Context, m *storage.ERC4337UserOp) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockIERC4337UserOpsMockRecorder) Save(ctx, m any) *MockIERC4337UserOpsSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIERC4337UserOps)(nil).Save), ctx, m)
	return &MockIERC4337UserOpsSaveCall{Call: call}
}

// MockIERC4337UserOpsSaveCall wrap *gomock.Call
type MockIERC4337UserOpsSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIERC4337UserOpsSaveCall) Return(arg0 error) *MockIERC4337UserOpsSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIERC4337UserOpsSaveCall) Do(f func(context.Context, *storage.ERC4337UserOp) error) *MockIERC4337UserOpsSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIERC4337UserOpsSaveCall) DoAndReturn(f func(context.Context, *storage.ERC4337UserOp) error) *MockIERC4337UserOpsSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m_2 *MockIERC4337UserOps) Update(ctx context.Context, m *storage.ERC4337UserOp) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIERC4337UserOpsMockRecorder) Update(ctx, m any) *MockIERC4337UserOpsUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIERC4337UserOps)(nil).Update), ctx, m)
	return &MockIERC4337UserOpsUpdateCall{Call: call}
}

// MockIERC4337UserOpsUpdateCall wrap *gomock.Call
type MockIERC4337UserOpsUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIERC4337UserOpsUpdateCall) Return(arg0 error) *MockIERC4337UserOpsUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIERC4337UserOpsUpdateCall) Do(f func(context.Context, *storage.ERC4337UserOp) error) *MockIERC4337UserOpsUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIERC4337UserOpsUpdateCall) DoAndReturn(f func(context.Context, *storage.ERC4337UserOp) error) *MockIERC4337UserOpsUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
