// Code generated by MockGen. DO NOT EDIT.
// Source: log.go
//
// Generated by this command:
//
//	mockgen -source=log.go -destination=mock/log.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	storage "github.com/baking-bad/noble-indexer/internal/storage"
	storage0 "github.com/dipdup-net/indexer-sdk/pkg/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockILog is a mock of ILog interface.
type MockILog struct {
	ctrl     *gomock.Controller
	recorder *MockILogMockRecorder
	isgomock struct{}
}

// MockILogMockRecorder is the mock recorder for MockILog.
type MockILogMockRecorder struct {
	mock *MockILog
}

// NewMockILog creates a new mock instance.
func NewMockILog(ctrl *gomock.Controller) *MockILog {
	mock := &MockILog{ctrl: ctrl}
	mock.recorder = &MockILogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILog) EXPECT() *MockILogMockRecorder {
	return m.recorder
}

// CursorList mocks base method.
func (m *MockILog) CursorList(ctx context.Context, id, limit uint64, order storage0.SortOrder, cmp storage0.Comparator) ([]*storage.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CursorList", ctx, id, limit, order, cmp)
	ret0, _ := ret[0].([]*storage.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CursorList indicates an expected call of CursorList.
func (mr *MockILogMockRecorder) CursorList(ctx, id, limit, order, cmp any) *MockILogCursorListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CursorList", reflect.TypeOf((*MockILog)(nil).CursorList), ctx, id, limit, order, cmp)
	return &MockILogCursorListCall{Call: call}
}

// MockILogCursorListCall wrap *gomock.Call
type MockILogCursorListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockILogCursorListCall) Return(arg0 []*storage.Log, arg1 error) *MockILogCursorListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockILogCursorListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.Log, error)) *MockILogCursorListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockILogCursorListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.Log, error)) *MockILogCursorListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Filter mocks base method.
func (m *MockILog) Filter(ctx context.Context, filter storage.LogListFilter) ([]storage.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, filter)
	ret0, _ := ret[0].([]storage.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *MockILogMockRecorder) Filter(ctx, filter any) *MockILogFilterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*MockILog)(nil).Filter), ctx, filter)
	return &MockILogFilterCall{Call: call}
}

// MockILogFilterCall wrap *gomock.Call
type MockILogFilterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockILogFilterCall) Return(arg0 []storage.Log, arg1 error) *MockILogFilterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockILogFilterCall) Do(f func(context.Context, storage.LogListFilter) ([]storage.Log, error)) *MockILogFilterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockILogFilterCall) DoAndReturn(f func(context.Context, storage.LogListFilter) ([]storage.Log, error)) *MockILogFilterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockILog) GetByID(ctx context.Context, id uint64) (*storage.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*storage.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockILogMockRecorder) GetByID(ctx, id any) *MockILogGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockILog)(nil).GetByID), ctx, id)
	return &MockILogGetByIDCall{Call: call}
}

// MockILogGetByIDCall wrap *gomock.Call
type MockILogGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockILogGetByIDCall) Return(arg0 *storage.Log, arg1 error) *MockILogGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockILogGetByIDCall) Do(f func(context.Context, uint64) (*storage.Log, error)) *MockILogGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockILogGetByIDCall) DoAndReturn(f func(context.Context, uint64) (*storage.Log, error)) *MockILogGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsNoRows mocks base method.
func (m *MockILog) IsNoRows(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNoRows", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNoRows indicates an expected call of IsNoRows.
func (mr *MockILogMockRecorder) IsNoRows(err any) *MockILogIsNoRowsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNoRows", reflect.TypeOf((*MockILog)(nil).IsNoRows), err)
	return &MockILogIsNoRowsCall{Call: call}
}

// MockILogIsNoRowsCall wrap *gomock.Call
type MockILogIsNoRowsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockILogIsNoRowsCall) Return(arg0 bool) *MockILogIsNoRowsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockILogIsNoRowsCall) Do(f func(error) bool) *MockILogIsNoRowsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockILogIsNoRowsCall) DoAndReturn(f func(error) bool) *MockILogIsNoRowsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LastID mocks base method.
func (m *MockILog) LastID(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastID", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastID indicates an expected call of LastID.
func (mr *MockILogMockRecorder) LastID(ctx any) *MockILogLastIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastID", reflect.TypeOf((*MockILog)(nil).LastID), ctx)
	return &MockILogLastIDCall{Call: call}
}

// MockILogLastIDCall wrap *gomock.Call
type MockILogLastIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockILogLastIDCall) Return(arg0 uint64, arg1 error) *MockILogLastIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockILogLastIDCall) Do(f func(context.Context) (uint64, error)) *MockILogLastIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockILogLastIDCall) DoAndReturn(f func(context.Context) (uint64, error)) *MockILogLastIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockILog) List(ctx context.Context, limit, offset uint64, order storage0.SortOrder) ([]*storage.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset, order)
	ret0, _ := ret[0].([]*storage.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockILogMockRecorder) List(ctx, limit, offset, order any) *MockILogListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockILog)(nil).List), ctx, limit, offset, order)
	return &MockILogListCall{Call: call}
}

// MockILogListCall wrap *gomock.Call
type MockILogListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockILogListCall) Return(arg0 []*storage.Log, arg1 error) *MockILogListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockILogListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.Log, error)) *MockILogListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockILogListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.Log, error)) *MockILogListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m_2 *MockILog) Save(ctx context.Context, m *storage.Log) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockILogMockRecorder) Save(ctx, m any) *MockILogSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockILog)(nil).Save), ctx, m)
	return &MockILogSaveCall{Call: call}
}

// MockILogSaveCall wrap *gomock.Call
type MockILogSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockILogSaveCall) Return(arg0 error) *MockILogSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockILogSaveCall) Do(f func(context.Context, *storage.Log) error) *MockILogSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockILogSaveCall) DoAndReturn(f func(context.Context, *storage.Log) error) *MockILogSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m_2 *MockILog) Update(ctx context.Context, m *storage.Log) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockILogMockRecorder) Update(ctx, m any) *MockILogUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockILog)(nil).Update), ctx, m)
	return &MockILogUpdateCall{Call: call}
}

// MockILogUpdateCall wrap *gomock.Call
type MockILogUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockILogUpdateCall) Return(arg0 error) *MockILogUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockILogUpdateCall) Do(f func(context.Context, *storage.Log) error) *MockILogUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockILogUpdateCall) DoAndReturn(f func(context.Context, *storage.Log) error) *MockILogUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
