// Code generated by MockGen. DO NOT EDIT.
// Source: proxy_contract.go
//
// Generated by this command:
//
//	mockgen -source=proxy_contract.go -destination=mock/proxy_contract.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	storage "github.com/NobleScope/noble-indexer/internal/storage"
	storage0 "github.com/dipdup-net/indexer-sdk/pkg/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockIProxyContract is a mock of IProxyContract interface.
type MockIProxyContract struct {
	ctrl     *gomock.Controller
	recorder *MockIProxyContractMockRecorder
	isgomock struct{}
}

// MockIProxyContractMockRecorder is the mock recorder for MockIProxyContract.
type MockIProxyContractMockRecorder struct {
	mock *MockIProxyContract
}

// NewMockIProxyContract creates a new mock instance.
func NewMockIProxyContract(ctrl *gomock.Controller) *MockIProxyContract {
	mock := &MockIProxyContract{ctrl: ctrl}
	mock.recorder = &MockIProxyContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProxyContract) EXPECT() *MockIProxyContractMockRecorder {
	return m.recorder
}

// CursorList mocks base method.
func (m *MockIProxyContract) CursorList(ctx context.Context, id, limit uint64, order storage0.SortOrder, cmp storage0.Comparator) ([]*storage.ProxyContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CursorList", ctx, id, limit, order, cmp)
	ret0, _ := ret[0].([]*storage.ProxyContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CursorList indicates an expected call of CursorList.
func (mr *MockIProxyContractMockRecorder) CursorList(ctx, id, limit, order, cmp any) *MockIProxyContractCursorListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CursorList", reflect.TypeOf((*MockIProxyContract)(nil).CursorList), ctx, id, limit, order, cmp)
	return &MockIProxyContractCursorListCall{Call: call}
}

// MockIProxyContractCursorListCall wrap *gomock.Call
type MockIProxyContractCursorListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIProxyContractCursorListCall) Return(arg0 []*storage.ProxyContract, arg1 error) *MockIProxyContractCursorListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIProxyContractCursorListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.ProxyContract, error)) *MockIProxyContractCursorListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIProxyContractCursorListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.ProxyContract, error)) *MockIProxyContractCursorListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FilteredList mocks base method.
func (m *MockIProxyContract) FilteredList(ctx context.Context, filters storage.ListProxyFilters) ([]storage.ProxyContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilteredList", ctx, filters)
	ret0, _ := ret[0].([]storage.ProxyContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilteredList indicates an expected call of FilteredList.
func (mr *MockIProxyContractMockRecorder) FilteredList(ctx, filters any) *MockIProxyContractFilteredListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilteredList", reflect.TypeOf((*MockIProxyContract)(nil).FilteredList), ctx, filters)
	return &MockIProxyContractFilteredListCall{Call: call}
}

// MockIProxyContractFilteredListCall wrap *gomock.Call
type MockIProxyContractFilteredListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIProxyContractFilteredListCall) Return(arg0 []storage.ProxyContract, arg1 error) *MockIProxyContractFilteredListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIProxyContractFilteredListCall) Do(f func(context.Context, storage.ListProxyFilters) ([]storage.ProxyContract, error)) *MockIProxyContractFilteredListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIProxyContractFilteredListCall) DoAndReturn(f func(context.Context, storage.ListProxyFilters) ([]storage.ProxyContract, error)) *MockIProxyContractFilteredListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockIProxyContract) GetByID(ctx context.Context, id uint64) (*storage.ProxyContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*storage.ProxyContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIProxyContractMockRecorder) GetByID(ctx, id any) *MockIProxyContractGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIProxyContract)(nil).GetByID), ctx, id)
	return &MockIProxyContractGetByIDCall{Call: call}
}

// MockIProxyContractGetByIDCall wrap *gomock.Call
type MockIProxyContractGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIProxyContractGetByIDCall) Return(arg0 *storage.ProxyContract, arg1 error) *MockIProxyContractGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIProxyContractGetByIDCall) Do(f func(context.Context, uint64) (*storage.ProxyContract, error)) *MockIProxyContractGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIProxyContractGetByIDCall) DoAndReturn(f func(context.Context, uint64) (*storage.ProxyContract, error)) *MockIProxyContractGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsNoRows mocks base method.
func (m *MockIProxyContract) IsNoRows(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNoRows", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNoRows indicates an expected call of IsNoRows.
func (mr *MockIProxyContractMockRecorder) IsNoRows(err any) *MockIProxyContractIsNoRowsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNoRows", reflect.TypeOf((*MockIProxyContract)(nil).IsNoRows), err)
	return &MockIProxyContractIsNoRowsCall{Call: call}
}

// MockIProxyContractIsNoRowsCall wrap *gomock.Call
type MockIProxyContractIsNoRowsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIProxyContractIsNoRowsCall) Return(arg0 bool) *MockIProxyContractIsNoRowsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIProxyContractIsNoRowsCall) Do(f func(error) bool) *MockIProxyContractIsNoRowsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIProxyContractIsNoRowsCall) DoAndReturn(f func(error) bool) *MockIProxyContractIsNoRowsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LastID mocks base method.
func (m *MockIProxyContract) LastID(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastID", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastID indicates an expected call of LastID.
func (mr *MockIProxyContractMockRecorder) LastID(ctx any) *MockIProxyContractLastIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastID", reflect.TypeOf((*MockIProxyContract)(nil).LastID), ctx)
	return &MockIProxyContractLastIDCall{Call: call}
}

// MockIProxyContractLastIDCall wrap *gomock.Call
type MockIProxyContractLastIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIProxyContractLastIDCall) Return(arg0 uint64, arg1 error) *MockIProxyContractLastIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIProxyContractLastIDCall) Do(f func(context.Context) (uint64, error)) *MockIProxyContractLastIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIProxyContractLastIDCall) DoAndReturn(f func(context.Context) (uint64, error)) *MockIProxyContractLastIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockIProxyContract) List(ctx context.Context, limit, offset uint64, order storage0.SortOrder) ([]*storage.ProxyContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset, order)
	ret0, _ := ret[0].([]*storage.ProxyContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIProxyContractMockRecorder) List(ctx, limit, offset, order any) *MockIProxyContractListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIProxyContract)(nil).List), ctx, limit, offset, order)
	return &MockIProxyContractListCall{Call: call}
}

// MockIProxyContractListCall wrap *gomock.Call
type MockIProxyContractListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIProxyContractListCall) Return(arg0 []*storage.ProxyContract, arg1 error) *MockIProxyContractListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIProxyContractListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.ProxyContract, error)) *MockIProxyContractListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIProxyContractListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.ProxyContract, error)) *MockIProxyContractListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NotResolved mocks base method.
func (m *MockIProxyContract) NotResolved(ctx context.Context) ([]storage.ProxyContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotResolved", ctx)
	ret0, _ := ret[0].([]storage.ProxyContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NotResolved indicates an expected call of NotResolved.
func (mr *MockIProxyContractMockRecorder) NotResolved(ctx any) *MockIProxyContractNotResolvedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotResolved", reflect.TypeOf((*MockIProxyContract)(nil).NotResolved), ctx)
	return &MockIProxyContractNotResolvedCall{Call: call}
}

// MockIProxyContractNotResolvedCall wrap *gomock.Call
type MockIProxyContractNotResolvedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIProxyContractNotResolvedCall) Return(contracts []storage.ProxyContract, err error) *MockIProxyContractNotResolvedCall {
	c.Call = c.Call.Return(contracts, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIProxyContractNotResolvedCall) Do(f func(context.Context) ([]storage.ProxyContract, error)) *MockIProxyContractNotResolvedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIProxyContractNotResolvedCall) DoAndReturn(f func(context.Context) ([]storage.ProxyContract, error)) *MockIProxyContractNotResolvedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m_2 *MockIProxyContract) Save(ctx context.Context, m *storage.ProxyContract) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockIProxyContractMockRecorder) Save(ctx, m any) *MockIProxyContractSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIProxyContract)(nil).Save), ctx, m)
	return &MockIProxyContractSaveCall{Call: call}
}

// MockIProxyContractSaveCall wrap *gomock.Call
type MockIProxyContractSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIProxyContractSaveCall) Return(arg0 error) *MockIProxyContractSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIProxyContractSaveCall) Do(f func(context.Context, *storage.ProxyContract) error) *MockIProxyContractSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIProxyContractSaveCall) DoAndReturn(f func(context.Context, *storage.ProxyContract) error) *MockIProxyContractSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m_2 *MockIProxyContract) Update(ctx context.Context, m *storage.ProxyContract) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIProxyContractMockRecorder) Update(ctx, m any) *MockIProxyContractUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIProxyContract)(nil).Update), ctx, m)
	return &MockIProxyContractUpdateCall{Call: call}
}

// MockIProxyContractUpdateCall wrap *gomock.Call
type MockIProxyContractUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIProxyContractUpdateCall) Return(arg0 error) *MockIProxyContractUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIProxyContractUpdateCall) Do(f func(context.Context, *storage.ProxyContract) error) *MockIProxyContractUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIProxyContractUpdateCall) DoAndReturn(f func(context.Context, *storage.ProxyContract) error) *MockIProxyContractUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
