// Code generated by MockGen. DO NOT EDIT.
// Source: source.go
//
// Generated by this command:
//
//	mockgen -source=source.go -destination=mock/source.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	storage "github.com/NobleScope/noble-indexer/internal/storage"
	storage0 "github.com/dipdup-net/indexer-sdk/pkg/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockISource is a mock of ISource interface.
type MockISource struct {
	ctrl     *gomock.Controller
	recorder *MockISourceMockRecorder
	isgomock struct{}
}

// MockISourceMockRecorder is the mock recorder for MockISource.
type MockISourceMockRecorder struct {
	mock *MockISource
}

// NewMockISource creates a new mock instance.
func NewMockISource(ctrl *gomock.Controller) *MockISource {
	mock := &MockISource{ctrl: ctrl}
	mock.recorder = &MockISourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISource) EXPECT() *MockISourceMockRecorder {
	return m.recorder
}

// ByContractId mocks base method.
func (m *MockISource) ByContractId(ctx context.Context, id uint64, limit, offset int) ([]storage.Source, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByContractId", ctx, id, limit, offset)
	ret0, _ := ret[0].([]storage.Source)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByContractId indicates an expected call of ByContractId.
func (mr *MockISourceMockRecorder) ByContractId(ctx, id, limit, offset any) *MockISourceByContractIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByContractId", reflect.TypeOf((*MockISource)(nil).ByContractId), ctx, id, limit, offset)
	return &MockISourceByContractIdCall{Call: call}
}

// MockISourceByContractIdCall wrap *gomock.Call
type MockISourceByContractIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockISourceByContractIdCall) Return(arg0 []storage.Source, arg1 error) *MockISourceByContractIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockISourceByContractIdCall) Do(f func(context.Context, uint64, int, int) ([]storage.Source, error)) *MockISourceByContractIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockISourceByContractIdCall) DoAndReturn(f func(context.Context, uint64, int, int) ([]storage.Source, error)) *MockISourceByContractIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CursorList mocks base method.
func (m *MockISource) CursorList(ctx context.Context, id, limit uint64, order storage0.SortOrder, cmp storage0.Comparator) ([]*storage.Source, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CursorList", ctx, id, limit, order, cmp)
	ret0, _ := ret[0].([]*storage.Source)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CursorList indicates an expected call of CursorList.
func (mr *MockISourceMockRecorder) CursorList(ctx, id, limit, order, cmp any) *MockISourceCursorListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CursorList", reflect.TypeOf((*MockISource)(nil).CursorList), ctx, id, limit, order, cmp)
	return &MockISourceCursorListCall{Call: call}
}

// MockISourceCursorListCall wrap *gomock.Call
type MockISourceCursorListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockISourceCursorListCall) Return(arg0 []*storage.Source, arg1 error) *MockISourceCursorListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockISourceCursorListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.Source, error)) *MockISourceCursorListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockISourceCursorListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.Source, error)) *MockISourceCursorListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockISource) GetByID(ctx context.Context, id uint64) (*storage.Source, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*storage.Source)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockISourceMockRecorder) GetByID(ctx, id any) *MockISourceGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockISource)(nil).GetByID), ctx, id)
	return &MockISourceGetByIDCall{Call: call}
}

// MockISourceGetByIDCall wrap *gomock.Call
type MockISourceGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockISourceGetByIDCall) Return(arg0 *storage.Source, arg1 error) *MockISourceGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockISourceGetByIDCall) Do(f func(context.Context, uint64) (*storage.Source, error)) *MockISourceGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockISourceGetByIDCall) DoAndReturn(f func(context.Context, uint64) (*storage.Source, error)) *MockISourceGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsNoRows mocks base method.
func (m *MockISource) IsNoRows(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNoRows", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNoRows indicates an expected call of IsNoRows.
func (mr *MockISourceMockRecorder) IsNoRows(err any) *MockISourceIsNoRowsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNoRows", reflect.TypeOf((*MockISource)(nil).IsNoRows), err)
	return &MockISourceIsNoRowsCall{Call: call}
}

// MockISourceIsNoRowsCall wrap *gomock.Call
type MockISourceIsNoRowsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockISourceIsNoRowsCall) Return(arg0 bool) *MockISourceIsNoRowsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockISourceIsNoRowsCall) Do(f func(error) bool) *MockISourceIsNoRowsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockISourceIsNoRowsCall) DoAndReturn(f func(error) bool) *MockISourceIsNoRowsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LastID mocks base method.
func (m *MockISource) LastID(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastID", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastID indicates an expected call of LastID.
func (mr *MockISourceMockRecorder) LastID(ctx any) *MockISourceLastIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastID", reflect.TypeOf((*MockISource)(nil).LastID), ctx)
	return &MockISourceLastIDCall{Call: call}
}

// MockISourceLastIDCall wrap *gomock.Call
type MockISourceLastIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockISourceLastIDCall) Return(arg0 uint64, arg1 error) *MockISourceLastIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockISourceLastIDCall) Do(f func(context.Context) (uint64, error)) *MockISourceLastIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockISourceLastIDCall) DoAndReturn(f func(context.Context) (uint64, error)) *MockISourceLastIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockISource) List(ctx context.Context, limit, offset uint64, order storage0.SortOrder) ([]*storage.Source, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset, order)
	ret0, _ := ret[0].([]*storage.Source)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockISourceMockRecorder) List(ctx, limit, offset, order any) *MockISourceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockISource)(nil).List), ctx, limit, offset, order)
	return &MockISourceListCall{Call: call}
}

// MockISourceListCall wrap *gomock.Call
type MockISourceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockISourceListCall) Return(arg0 []*storage.Source, arg1 error) *MockISourceListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockISourceListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.Source, error)) *MockISourceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockISourceListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.Source, error)) *MockISourceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m_2 *MockISource) Save(ctx context.Context, m *storage.Source) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockISourceMockRecorder) Save(ctx, m any) *MockISourceSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockISource)(nil).Save), ctx, m)
	return &MockISourceSaveCall{Call: call}
}

// MockISourceSaveCall wrap *gomock.Call
type MockISourceSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockISourceSaveCall) Return(arg0 error) *MockISourceSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockISourceSaveCall) Do(f func(context.Context, *storage.Source) error) *MockISourceSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockISourceSaveCall) DoAndReturn(f func(context.Context, *storage.Source) error) *MockISourceSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m_2 *MockISource) Update(ctx context.Context, m *storage.Source) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockISourceMockRecorder) Update(ctx, m any) *MockISourceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockISource)(nil).Update), ctx, m)
	return &MockISourceUpdateCall{Call: call}
}

// MockISourceUpdateCall wrap *gomock.Call
type MockISourceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockISourceUpdateCall) Return(arg0 error) *MockISourceUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockISourceUpdateCall) Do(f func(context.Context, *storage.Source) error) *MockISourceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockISourceUpdateCall) DoAndReturn(f func(context.Context, *storage.Source) error) *MockISourceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
