// Code generated by MockGen. DO NOT EDIT.
// Source: token_balance.go
//
// Generated by this command:
//
//	mockgen -source=token_balance.go -destination=mock/token_balance.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	storage "github.com/NobleScope/noble-indexer/internal/storage"
	storage0 "github.com/dipdup-net/indexer-sdk/pkg/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockITokenBalance is a mock of ITokenBalance interface.
type MockITokenBalance struct {
	ctrl     *gomock.Controller
	recorder *MockITokenBalanceMockRecorder
	isgomock struct{}
}

// MockITokenBalanceMockRecorder is the mock recorder for MockITokenBalance.
type MockITokenBalanceMockRecorder struct {
	mock *MockITokenBalance
}

// NewMockITokenBalance creates a new mock instance.
func NewMockITokenBalance(ctrl *gomock.Controller) *MockITokenBalance {
	mock := &MockITokenBalance{ctrl: ctrl}
	mock.recorder = &MockITokenBalanceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITokenBalance) EXPECT() *MockITokenBalanceMockRecorder {
	return m.recorder
}

// CursorList mocks base method.
func (m *MockITokenBalance) CursorList(ctx context.Context, id, limit uint64, order storage0.SortOrder, cmp storage0.Comparator) ([]*storage.TokenBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CursorList", ctx, id, limit, order, cmp)
	ret0, _ := ret[0].([]*storage.TokenBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CursorList indicates an expected call of CursorList.
func (mr *MockITokenBalanceMockRecorder) CursorList(ctx, id, limit, order, cmp any) *MockITokenBalanceCursorListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CursorList", reflect.TypeOf((*MockITokenBalance)(nil).CursorList), ctx, id, limit, order, cmp)
	return &MockITokenBalanceCursorListCall{Call: call}
}

// MockITokenBalanceCursorListCall wrap *gomock.Call
type MockITokenBalanceCursorListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITokenBalanceCursorListCall) Return(arg0 []*storage.TokenBalance, arg1 error) *MockITokenBalanceCursorListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITokenBalanceCursorListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.TokenBalance, error)) *MockITokenBalanceCursorListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITokenBalanceCursorListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.TokenBalance, error)) *MockITokenBalanceCursorListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Filter mocks base method.
func (m *MockITokenBalance) Filter(ctx context.Context, filter storage.TokenBalanceListFilter) ([]storage.TokenBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, filter)
	ret0, _ := ret[0].([]storage.TokenBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *MockITokenBalanceMockRecorder) Filter(ctx, filter any) *MockITokenBalanceFilterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*MockITokenBalance)(nil).Filter), ctx, filter)
	return &MockITokenBalanceFilterCall{Call: call}
}

// MockITokenBalanceFilterCall wrap *gomock.Call
type MockITokenBalanceFilterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITokenBalanceFilterCall) Return(arg0 []storage.TokenBalance, arg1 error) *MockITokenBalanceFilterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITokenBalanceFilterCall) Do(f func(context.Context, storage.TokenBalanceListFilter) ([]storage.TokenBalance, error)) *MockITokenBalanceFilterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITokenBalanceFilterCall) DoAndReturn(f func(context.Context, storage.TokenBalanceListFilter) ([]storage.TokenBalance, error)) *MockITokenBalanceFilterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockITokenBalance) GetByID(ctx context.Context, id uint64) (*storage.TokenBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*storage.TokenBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockITokenBalanceMockRecorder) GetByID(ctx, id any) *MockITokenBalanceGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockITokenBalance)(nil).GetByID), ctx, id)
	return &MockITokenBalanceGetByIDCall{Call: call}
}

// MockITokenBalanceGetByIDCall wrap *gomock.Call
type MockITokenBalanceGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITokenBalanceGetByIDCall) Return(arg0 *storage.TokenBalance, arg1 error) *MockITokenBalanceGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITokenBalanceGetByIDCall) Do(f func(context.Context, uint64) (*storage.TokenBalance, error)) *MockITokenBalanceGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITokenBalanceGetByIDCall) DoAndReturn(f func(context.Context, uint64) (*storage.TokenBalance, error)) *MockITokenBalanceGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsNoRows mocks base method.
func (m *MockITokenBalance) IsNoRows(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNoRows", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNoRows indicates an expected call of IsNoRows.
func (mr *MockITokenBalanceMockRecorder) IsNoRows(err any) *MockITokenBalanceIsNoRowsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNoRows", reflect.TypeOf((*MockITokenBalance)(nil).IsNoRows), err)
	return &MockITokenBalanceIsNoRowsCall{Call: call}
}

// MockITokenBalanceIsNoRowsCall wrap *gomock.Call
type MockITokenBalanceIsNoRowsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITokenBalanceIsNoRowsCall) Return(arg0 bool) *MockITokenBalanceIsNoRowsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITokenBalanceIsNoRowsCall) Do(f func(error) bool) *MockITokenBalanceIsNoRowsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITokenBalanceIsNoRowsCall) DoAndReturn(f func(error) bool) *MockITokenBalanceIsNoRowsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LastID mocks base method.
func (m *MockITokenBalance) LastID(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastID", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastID indicates an expected call of LastID.
func (mr *MockITokenBalanceMockRecorder) LastID(ctx any) *MockITokenBalanceLastIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastID", reflect.TypeOf((*MockITokenBalance)(nil).LastID), ctx)
	return &MockITokenBalanceLastIDCall{Call: call}
}

// MockITokenBalanceLastIDCall wrap *gomock.Call
type MockITokenBalanceLastIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITokenBalanceLastIDCall) Return(arg0 uint64, arg1 error) *MockITokenBalanceLastIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITokenBalanceLastIDCall) Do(f func(context.Context) (uint64, error)) *MockITokenBalanceLastIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITokenBalanceLastIDCall) DoAndReturn(f func(context.Context) (uint64, error)) *MockITokenBalanceLastIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockITokenBalance) List(ctx context.Context, limit, offset uint64, order storage0.SortOrder) ([]*storage.TokenBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset, order)
	ret0, _ := ret[0].([]*storage.TokenBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockITokenBalanceMockRecorder) List(ctx, limit, offset, order any) *MockITokenBalanceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockITokenBalance)(nil).List), ctx, limit, offset, order)
	return &MockITokenBalanceListCall{Call: call}
}

// MockITokenBalanceListCall wrap *gomock.Call
type MockITokenBalanceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITokenBalanceListCall) Return(arg0 []*storage.TokenBalance, arg1 error) *MockITokenBalanceListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITokenBalanceListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.TokenBalance, error)) *MockITokenBalanceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITokenBalanceListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.TokenBalance, error)) *MockITokenBalanceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m_2 *MockITokenBalance) Save(ctx context.Context, m *storage.TokenBalance) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockITokenBalanceMockRecorder) Save(ctx, m any) *MockITokenBalanceSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockITokenBalance)(nil).Save), ctx, m)
	return &MockITokenBalanceSaveCall{Call: call}
}

// MockITokenBalanceSaveCall wrap *gomock.Call
type MockITokenBalanceSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITokenBalanceSaveCall) Return(arg0 error) *MockITokenBalanceSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITokenBalanceSaveCall) Do(f func(context.Context, *storage.TokenBalance) error) *MockITokenBalanceSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITokenBalanceSaveCall) DoAndReturn(f func(context.Context, *storage.TokenBalance) error) *MockITokenBalanceSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m_2 *MockITokenBalance) Update(ctx context.Context, m *storage.TokenBalance) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockITokenBalanceMockRecorder) Update(ctx, m any) *MockITokenBalanceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockITokenBalance)(nil).Update), ctx, m)
	return &MockITokenBalanceUpdateCall{Call: call}
}

// MockITokenBalanceUpdateCall wrap *gomock.Call
type MockITokenBalanceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITokenBalanceUpdateCall) Return(arg0 error) *MockITokenBalanceUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITokenBalanceUpdateCall) Do(f func(context.Context, *storage.TokenBalance) error) *MockITokenBalanceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITokenBalanceUpdateCall) DoAndReturn(f func(context.Context, *storage.TokenBalance) error) *MockITokenBalanceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
