// Code generated by MockGen. DO NOT EDIT.
// Source: token.go
//
// Generated by this command:
//
//	mockgen -source=token.go -destination=mock/token.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	storage "github.com/NobleScope/noble-indexer/internal/storage"
	storage0 "github.com/dipdup-net/indexer-sdk/pkg/storage"
	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockIToken is a mock of IToken interface.
type MockIToken struct {
	ctrl     *gomock.Controller
	recorder *MockITokenMockRecorder
	isgomock struct{}
}

// MockITokenMockRecorder is the mock recorder for MockIToken.
type MockITokenMockRecorder struct {
	mock *MockIToken
}

// NewMockIToken creates a new mock instance.
func NewMockIToken(ctrl *gomock.Controller) *MockIToken {
	mock := &MockIToken{ctrl: ctrl}
	mock.recorder = &MockITokenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIToken) EXPECT() *MockITokenMockRecorder {
	return m.recorder
}

// CursorList mocks base method.
func (m *MockIToken) CursorList(ctx context.Context, id, limit uint64, order storage0.SortOrder, cmp storage0.Comparator) ([]*storage.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CursorList", ctx, id, limit, order, cmp)
	ret0, _ := ret[0].([]*storage.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CursorList indicates an expected call of CursorList.
func (mr *MockITokenMockRecorder) CursorList(ctx, id, limit, order, cmp any) *MockITokenCursorListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CursorList", reflect.TypeOf((*MockIToken)(nil).CursorList), ctx, id, limit, order, cmp)
	return &MockITokenCursorListCall{Call: call}
}

// MockITokenCursorListCall wrap *gomock.Call
type MockITokenCursorListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITokenCursorListCall) Return(arg0 []*storage.Token, arg1 error) *MockITokenCursorListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITokenCursorListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.Token, error)) *MockITokenCursorListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITokenCursorListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.Token, error)) *MockITokenCursorListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Filter mocks base method.
func (m *MockIToken) Filter(ctx context.Context, filter storage.TokenListFilter) ([]storage.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, filter)
	ret0, _ := ret[0].([]storage.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *MockITokenMockRecorder) Filter(ctx, filter any) *MockITokenFilterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*MockIToken)(nil).Filter), ctx, filter)
	return &MockITokenFilterCall{Call: call}
}

// MockITokenFilterCall wrap *gomock.Call
type MockITokenFilterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITokenFilterCall) Return(arg0 []storage.Token, arg1 error) *MockITokenFilterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITokenFilterCall) Do(f func(context.Context, storage.TokenListFilter) ([]storage.Token, error)) *MockITokenFilterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITokenFilterCall) DoAndReturn(f func(context.Context, storage.TokenListFilter) ([]storage.Token, error)) *MockITokenFilterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockIToken) Get(ctx context.Context, contractId uint64, tokenId decimal.Decimal) (storage.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, contractId, tokenId)
	ret0, _ := ret[0].(storage.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockITokenMockRecorder) Get(ctx, contractId, tokenId any) *MockITokenGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIToken)(nil).Get), ctx, contractId, tokenId)
	return &MockITokenGetCall{Call: call}
}

// MockITokenGetCall wrap *gomock.Call
type MockITokenGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITokenGetCall) Return(arg0 storage.Token, arg1 error) *MockITokenGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITokenGetCall) Do(f func(context.Context, uint64, decimal.Decimal) (storage.Token, error)) *MockITokenGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITokenGetCall) DoAndReturn(f func(context.Context, uint64, decimal.Decimal) (storage.Token, error)) *MockITokenGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockIToken) GetByID(ctx context.Context, id uint64) (*storage.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*storage.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockITokenMockRecorder) GetByID(ctx, id any) *MockITokenGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIToken)(nil).GetByID), ctx, id)
	return &MockITokenGetByIDCall{Call: call}
}

// MockITokenGetByIDCall wrap *gomock.Call
type MockITokenGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITokenGetByIDCall) Return(arg0 *storage.Token, arg1 error) *MockITokenGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITokenGetByIDCall) Do(f func(context.Context, uint64) (*storage.Token, error)) *MockITokenGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITokenGetByIDCall) DoAndReturn(f func(context.Context, uint64) (*storage.Token, error)) *MockITokenGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsNoRows mocks base method.
func (m *MockIToken) IsNoRows(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNoRows", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNoRows indicates an expected call of IsNoRows.
func (mr *MockITokenMockRecorder) IsNoRows(err any) *MockITokenIsNoRowsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNoRows", reflect.TypeOf((*MockIToken)(nil).IsNoRows), err)
	return &MockITokenIsNoRowsCall{Call: call}
}

// MockITokenIsNoRowsCall wrap *gomock.Call
type MockITokenIsNoRowsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITokenIsNoRowsCall) Return(arg0 bool) *MockITokenIsNoRowsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITokenIsNoRowsCall) Do(f func(error) bool) *MockITokenIsNoRowsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITokenIsNoRowsCall) DoAndReturn(f func(error) bool) *MockITokenIsNoRowsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LastID mocks base method.
func (m *MockIToken) LastID(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastID", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastID indicates an expected call of LastID.
func (mr *MockITokenMockRecorder) LastID(ctx any) *MockITokenLastIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastID", reflect.TypeOf((*MockIToken)(nil).LastID), ctx)
	return &MockITokenLastIDCall{Call: call}
}

// MockITokenLastIDCall wrap *gomock.Call
type MockITokenLastIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITokenLastIDCall) Return(arg0 uint64, arg1 error) *MockITokenLastIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITokenLastIDCall) Do(f func(context.Context) (uint64, error)) *MockITokenLastIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITokenLastIDCall) DoAndReturn(f func(context.Context) (uint64, error)) *MockITokenLastIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockIToken) List(ctx context.Context, limit, offset uint64, order storage0.SortOrder) ([]*storage.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset, order)
	ret0, _ := ret[0].([]*storage.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockITokenMockRecorder) List(ctx, limit, offset, order any) *MockITokenListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIToken)(nil).List), ctx, limit, offset, order)
	return &MockITokenListCall{Call: call}
}

// MockITokenListCall wrap *gomock.Call
type MockITokenListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITokenListCall) Return(arg0 []*storage.Token, arg1 error) *MockITokenListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITokenListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.Token, error)) *MockITokenListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITokenListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.Token, error)) *MockITokenListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PendingMetadata mocks base method.
func (m *MockIToken) PendingMetadata(ctx context.Context, delay time.Duration, limit int) ([]*storage.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingMetadata", ctx, delay, limit)
	ret0, _ := ret[0].([]*storage.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PendingMetadata indicates an expected call of PendingMetadata.
func (mr *MockITokenMockRecorder) PendingMetadata(ctx, delay, limit any) *MockITokenPendingMetadataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingMetadata", reflect.TypeOf((*MockIToken)(nil).PendingMetadata), ctx, delay, limit)
	return &MockITokenPendingMetadataCall{Call: call}
}

// MockITokenPendingMetadataCall wrap *gomock.Call
type MockITokenPendingMetadataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITokenPendingMetadataCall) Return(arg0 []*storage.Token, arg1 error) *MockITokenPendingMetadataCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITokenPendingMetadataCall) Do(f func(context.Context, time.Duration, int) ([]*storage.Token, error)) *MockITokenPendingMetadataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITokenPendingMetadataCall) DoAndReturn(f func(context.Context, time.Duration, int) ([]*storage.Token, error)) *MockITokenPendingMetadataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m_2 *MockIToken) Save(ctx context.Context, m *storage.Token) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockITokenMockRecorder) Save(ctx, m any) *MockITokenSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIToken)(nil).Save), ctx, m)
	return &MockITokenSaveCall{Call: call}
}

// MockITokenSaveCall wrap *gomock.Call
type MockITokenSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITokenSaveCall) Return(arg0 error) *MockITokenSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITokenSaveCall) Do(f func(context.Context, *storage.Token) error) *MockITokenSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITokenSaveCall) DoAndReturn(f func(context.Context, *storage.Token) error) *MockITokenSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m_2 *MockIToken) Update(ctx context.Context, m *storage.Token) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockITokenMockRecorder) Update(ctx, m any) *MockITokenUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIToken)(nil).Update), ctx, m)
	return &MockITokenUpdateCall{Call: call}
}

// MockITokenUpdateCall wrap *gomock.Call
type MockITokenUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITokenUpdateCall) Return(arg0 error) *MockITokenUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITokenUpdateCall) Do(f func(context.Context, *storage.Token) error) *MockITokenUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITokenUpdateCall) DoAndReturn(f func(context.Context, *storage.Token) error) *MockITokenUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
