// Code generated by MockGen. DO NOT EDIT.
// Source: trace.go
//
// Generated by this command:
//
//	mockgen -source=trace.go -destination=mock/trace.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	storage "github.com/NobleScope/noble-indexer/internal/storage"
	storage0 "github.com/dipdup-net/indexer-sdk/pkg/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockITrace is a mock of ITrace interface.
type MockITrace struct {
	ctrl     *gomock.Controller
	recorder *MockITraceMockRecorder
	isgomock struct{}
}

// MockITraceMockRecorder is the mock recorder for MockITrace.
type MockITraceMockRecorder struct {
	mock *MockITrace
}

// NewMockITrace creates a new mock instance.
func NewMockITrace(ctrl *gomock.Controller) *MockITrace {
	mock := &MockITrace{ctrl: ctrl}
	mock.recorder = &MockITraceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITrace) EXPECT() *MockITraceMockRecorder {
	return m.recorder
}

// ByTxId mocks base method.
func (m *MockITrace) ByTxId(ctx context.Context, txId uint64) ([]*storage.Trace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByTxId", ctx, txId)
	ret0, _ := ret[0].([]*storage.Trace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByTxId indicates an expected call of ByTxId.
func (mr *MockITraceMockRecorder) ByTxId(ctx, txId any) *MockITraceByTxIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByTxId", reflect.TypeOf((*MockITrace)(nil).ByTxId), ctx, txId)
	return &MockITraceByTxIdCall{Call: call}
}

// MockITraceByTxIdCall wrap *gomock.Call
type MockITraceByTxIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITraceByTxIdCall) Return(traces []*storage.Trace, err error) *MockITraceByTxIdCall {
	c.Call = c.Call.Return(traces, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITraceByTxIdCall) Do(f func(context.Context, uint64) ([]*storage.Trace, error)) *MockITraceByTxIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITraceByTxIdCall) DoAndReturn(f func(context.Context, uint64) ([]*storage.Trace, error)) *MockITraceByTxIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CursorList mocks base method.
func (m *MockITrace) CursorList(ctx context.Context, id, limit uint64, order storage0.SortOrder, cmp storage0.Comparator) ([]*storage.Trace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CursorList", ctx, id, limit, order, cmp)
	ret0, _ := ret[0].([]*storage.Trace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CursorList indicates an expected call of CursorList.
func (mr *MockITraceMockRecorder) CursorList(ctx, id, limit, order, cmp any) *MockITraceCursorListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CursorList", reflect.TypeOf((*MockITrace)(nil).CursorList), ctx, id, limit, order, cmp)
	return &MockITraceCursorListCall{Call: call}
}

// MockITraceCursorListCall wrap *gomock.Call
type MockITraceCursorListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITraceCursorListCall) Return(arg0 []*storage.Trace, arg1 error) *MockITraceCursorListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITraceCursorListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.Trace, error)) *MockITraceCursorListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITraceCursorListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.Trace, error)) *MockITraceCursorListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Filter mocks base method.
func (m *MockITrace) Filter(ctx context.Context, filter storage.TraceListFilter) ([]*storage.Trace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, filter)
	ret0, _ := ret[0].([]*storage.Trace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *MockITraceMockRecorder) Filter(ctx, filter any) *MockITraceFilterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*MockITrace)(nil).Filter), ctx, filter)
	return &MockITraceFilterCall{Call: call}
}

// MockITraceFilterCall wrap *gomock.Call
type MockITraceFilterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITraceFilterCall) Return(traces []*storage.Trace, err error) *MockITraceFilterCall {
	c.Call = c.Call.Return(traces, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITraceFilterCall) Do(f func(context.Context, storage.TraceListFilter) ([]*storage.Trace, error)) *MockITraceFilterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITraceFilterCall) DoAndReturn(f func(context.Context, storage.TraceListFilter) ([]*storage.Trace, error)) *MockITraceFilterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockITrace) GetByID(ctx context.Context, id uint64) (*storage.Trace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*storage.Trace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockITraceMockRecorder) GetByID(ctx, id any) *MockITraceGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockITrace)(nil).GetByID), ctx, id)
	return &MockITraceGetByIDCall{Call: call}
}

// MockITraceGetByIDCall wrap *gomock.Call
type MockITraceGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITraceGetByIDCall) Return(arg0 *storage.Trace, arg1 error) *MockITraceGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITraceGetByIDCall) Do(f func(context.Context, uint64) (*storage.Trace, error)) *MockITraceGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITraceGetByIDCall) DoAndReturn(f func(context.Context, uint64) (*storage.Trace, error)) *MockITraceGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsNoRows mocks base method.
func (m *MockITrace) IsNoRows(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNoRows", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNoRows indicates an expected call of IsNoRows.
func (mr *MockITraceMockRecorder) IsNoRows(err any) *MockITraceIsNoRowsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNoRows", reflect.TypeOf((*MockITrace)(nil).IsNoRows), err)
	return &MockITraceIsNoRowsCall{Call: call}
}

// MockITraceIsNoRowsCall wrap *gomock.Call
type MockITraceIsNoRowsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITraceIsNoRowsCall) Return(arg0 bool) *MockITraceIsNoRowsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITraceIsNoRowsCall) Do(f func(error) bool) *MockITraceIsNoRowsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITraceIsNoRowsCall) DoAndReturn(f func(error) bool) *MockITraceIsNoRowsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LastID mocks base method.
func (m *MockITrace) LastID(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastID", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastID indicates an expected call of LastID.
func (mr *MockITraceMockRecorder) LastID(ctx any) *MockITraceLastIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastID", reflect.TypeOf((*MockITrace)(nil).LastID), ctx)
	return &MockITraceLastIDCall{Call: call}
}

// MockITraceLastIDCall wrap *gomock.Call
type MockITraceLastIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITraceLastIDCall) Return(arg0 uint64, arg1 error) *MockITraceLastIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITraceLastIDCall) Do(f func(context.Context) (uint64, error)) *MockITraceLastIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITraceLastIDCall) DoAndReturn(f func(context.Context) (uint64, error)) *MockITraceLastIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockITrace) List(ctx context.Context, limit, offset uint64, order storage0.SortOrder) ([]*storage.Trace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset, order)
	ret0, _ := ret[0].([]*storage.Trace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockITraceMockRecorder) List(ctx, limit, offset, order any) *MockITraceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockITrace)(nil).List), ctx, limit, offset, order)
	return &MockITraceListCall{Call: call}
}

// MockITraceListCall wrap *gomock.Call
type MockITraceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITraceListCall) Return(arg0 []*storage.Trace, arg1 error) *MockITraceListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITraceListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.Trace, error)) *MockITraceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITraceListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.Trace, error)) *MockITraceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m_2 *MockITrace) Save(ctx context.Context, m *storage.Trace) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockITraceMockRecorder) Save(ctx, m any) *MockITraceSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockITrace)(nil).Save), ctx, m)
	return &MockITraceSaveCall{Call: call}
}

// MockITraceSaveCall wrap *gomock.Call
type MockITraceSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITraceSaveCall) Return(arg0 error) *MockITraceSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITraceSaveCall) Do(f func(context.Context, *storage.Trace) error) *MockITraceSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITraceSaveCall) DoAndReturn(f func(context.Context, *storage.Trace) error) *MockITraceSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m_2 *MockITrace) Update(ctx context.Context, m *storage.Trace) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockITraceMockRecorder) Update(ctx, m any) *MockITraceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockITrace)(nil).Update), ctx, m)
	return &MockITraceUpdateCall{Call: call}
}

// MockITraceUpdateCall wrap *gomock.Call
type MockITraceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITraceUpdateCall) Return(arg0 error) *MockITraceUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITraceUpdateCall) Do(f func(context.Context, *storage.Trace) error) *MockITraceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITraceUpdateCall) DoAndReturn(f func(context.Context, *storage.Trace) error) *MockITraceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
