// Code generated by MockGen. DO NOT EDIT.
// Source: verification_task.go
//
// Generated by this command:
//
//	mockgen -source=verification_task.go -destination=mock/verification_task.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	storage "github.com/baking-bad/noble-indexer/internal/storage"
	storage0 "github.com/dipdup-net/indexer-sdk/pkg/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockIVerificationTask is a mock of IVerificationTask interface.
type MockIVerificationTask struct {
	ctrl     *gomock.Controller
	recorder *MockIVerificationTaskMockRecorder
	isgomock struct{}
}

// MockIVerificationTaskMockRecorder is the mock recorder for MockIVerificationTask.
type MockIVerificationTaskMockRecorder struct {
	mock *MockIVerificationTask
}

// NewMockIVerificationTask creates a new mock instance.
func NewMockIVerificationTask(ctrl *gomock.Controller) *MockIVerificationTask {
	mock := &MockIVerificationTask{ctrl: ctrl}
	mock.recorder = &MockIVerificationTaskMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIVerificationTask) EXPECT() *MockIVerificationTaskMockRecorder {
	return m.recorder
}

// ByContractId mocks base method.
func (m *MockIVerificationTask) ByContractId(ctx context.Context, contractId uint64) (storage.VerificationTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByContractId", ctx, contractId)
	ret0, _ := ret[0].(storage.VerificationTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByContractId indicates an expected call of ByContractId.
func (mr *MockIVerificationTaskMockRecorder) ByContractId(ctx, contractId any) *MockIVerificationTaskByContractIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByContractId", reflect.TypeOf((*MockIVerificationTask)(nil).ByContractId), ctx, contractId)
	return &MockIVerificationTaskByContractIdCall{Call: call}
}

// MockIVerificationTaskByContractIdCall wrap *gomock.Call
type MockIVerificationTaskByContractIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVerificationTaskByContractIdCall) Return(arg0 storage.VerificationTask, arg1 error) *MockIVerificationTaskByContractIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVerificationTaskByContractIdCall) Do(f func(context.Context, uint64) (storage.VerificationTask, error)) *MockIVerificationTaskByContractIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVerificationTaskByContractIdCall) DoAndReturn(f func(context.Context, uint64) (storage.VerificationTask, error)) *MockIVerificationTaskByContractIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CursorList mocks base method.
func (m *MockIVerificationTask) CursorList(ctx context.Context, id, limit uint64, order storage0.SortOrder, cmp storage0.Comparator) ([]*storage.VerificationTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CursorList", ctx, id, limit, order, cmp)
	ret0, _ := ret[0].([]*storage.VerificationTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CursorList indicates an expected call of CursorList.
func (mr *MockIVerificationTaskMockRecorder) CursorList(ctx, id, limit, order, cmp any) *MockIVerificationTaskCursorListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CursorList", reflect.TypeOf((*MockIVerificationTask)(nil).CursorList), ctx, id, limit, order, cmp)
	return &MockIVerificationTaskCursorListCall{Call: call}
}

// MockIVerificationTaskCursorListCall wrap *gomock.Call
type MockIVerificationTaskCursorListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVerificationTaskCursorListCall) Return(arg0 []*storage.VerificationTask, arg1 error) *MockIVerificationTaskCursorListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVerificationTaskCursorListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.VerificationTask, error)) *MockIVerificationTaskCursorListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVerificationTaskCursorListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.VerificationTask, error)) *MockIVerificationTaskCursorListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockIVerificationTask) GetByID(ctx context.Context, id uint64) (*storage.VerificationTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*storage.VerificationTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIVerificationTaskMockRecorder) GetByID(ctx, id any) *MockIVerificationTaskGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIVerificationTask)(nil).GetByID), ctx, id)
	return &MockIVerificationTaskGetByIDCall{Call: call}
}

// MockIVerificationTaskGetByIDCall wrap *gomock.Call
type MockIVerificationTaskGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVerificationTaskGetByIDCall) Return(arg0 *storage.VerificationTask, arg1 error) *MockIVerificationTaskGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVerificationTaskGetByIDCall) Do(f func(context.Context, uint64) (*storage.VerificationTask, error)) *MockIVerificationTaskGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVerificationTaskGetByIDCall) DoAndReturn(f func(context.Context, uint64) (*storage.VerificationTask, error)) *MockIVerificationTaskGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsNoRows mocks base method.
func (m *MockIVerificationTask) IsNoRows(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNoRows", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNoRows indicates an expected call of IsNoRows.
func (mr *MockIVerificationTaskMockRecorder) IsNoRows(err any) *MockIVerificationTaskIsNoRowsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNoRows", reflect.TypeOf((*MockIVerificationTask)(nil).IsNoRows), err)
	return &MockIVerificationTaskIsNoRowsCall{Call: call}
}

// MockIVerificationTaskIsNoRowsCall wrap *gomock.Call
type MockIVerificationTaskIsNoRowsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVerificationTaskIsNoRowsCall) Return(arg0 bool) *MockIVerificationTaskIsNoRowsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVerificationTaskIsNoRowsCall) Do(f func(error) bool) *MockIVerificationTaskIsNoRowsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVerificationTaskIsNoRowsCall) DoAndReturn(f func(error) bool) *MockIVerificationTaskIsNoRowsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LastID mocks base method.
func (m *MockIVerificationTask) LastID(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastID", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastID indicates an expected call of LastID.
func (mr *MockIVerificationTaskMockRecorder) LastID(ctx any) *MockIVerificationTaskLastIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastID", reflect.TypeOf((*MockIVerificationTask)(nil).LastID), ctx)
	return &MockIVerificationTaskLastIDCall{Call: call}
}

// MockIVerificationTaskLastIDCall wrap *gomock.Call
type MockIVerificationTaskLastIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVerificationTaskLastIDCall) Return(arg0 uint64, arg1 error) *MockIVerificationTaskLastIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVerificationTaskLastIDCall) Do(f func(context.Context) (uint64, error)) *MockIVerificationTaskLastIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVerificationTaskLastIDCall) DoAndReturn(f func(context.Context) (uint64, error)) *MockIVerificationTaskLastIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Latest mocks base method.
func (m *MockIVerificationTask) Latest(ctx context.Context) (storage.VerificationTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Latest", ctx)
	ret0, _ := ret[0].(storage.VerificationTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Latest indicates an expected call of Latest.
func (mr *MockIVerificationTaskMockRecorder) Latest(ctx any) *MockIVerificationTaskLatestCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Latest", reflect.TypeOf((*MockIVerificationTask)(nil).Latest), ctx)
	return &MockIVerificationTaskLatestCall{Call: call}
}

// MockIVerificationTaskLatestCall wrap *gomock.Call
type MockIVerificationTaskLatestCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVerificationTaskLatestCall) Return(arg0 storage.VerificationTask, arg1 error) *MockIVerificationTaskLatestCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVerificationTaskLatestCall) Do(f func(context.Context) (storage.VerificationTask, error)) *MockIVerificationTaskLatestCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVerificationTaskLatestCall) DoAndReturn(f func(context.Context) (storage.VerificationTask, error)) *MockIVerificationTaskLatestCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockIVerificationTask) List(ctx context.Context, limit, offset uint64, order storage0.SortOrder) ([]*storage.VerificationTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset, order)
	ret0, _ := ret[0].([]*storage.VerificationTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIVerificationTaskMockRecorder) List(ctx, limit, offset, order any) *MockIVerificationTaskListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIVerificationTask)(nil).List), ctx, limit, offset, order)
	return &MockIVerificationTaskListCall{Call: call}
}

// MockIVerificationTaskListCall wrap *gomock.Call
type MockIVerificationTaskListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVerificationTaskListCall) Return(arg0 []*storage.VerificationTask, arg1 error) *MockIVerificationTaskListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVerificationTaskListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.VerificationTask, error)) *MockIVerificationTaskListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVerificationTaskListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.VerificationTask, error)) *MockIVerificationTaskListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m_2 *MockIVerificationTask) Save(ctx context.Context, m *storage.VerificationTask) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockIVerificationTaskMockRecorder) Save(ctx, m any) *MockIVerificationTaskSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIVerificationTask)(nil).Save), ctx, m)
	return &MockIVerificationTaskSaveCall{Call: call}
}

// MockIVerificationTaskSaveCall wrap *gomock.Call
type MockIVerificationTaskSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVerificationTaskSaveCall) Return(arg0 error) *MockIVerificationTaskSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVerificationTaskSaveCall) Do(f func(context.Context, *storage.VerificationTask) error) *MockIVerificationTaskSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVerificationTaskSaveCall) DoAndReturn(f func(context.Context, *storage.VerificationTask) error) *MockIVerificationTaskSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m_2 *MockIVerificationTask) Update(ctx context.Context, m *storage.VerificationTask) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIVerificationTaskMockRecorder) Update(ctx, m any) *MockIVerificationTaskUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIVerificationTask)(nil).Update), ctx, m)
	return &MockIVerificationTaskUpdateCall{Call: call}
}

// MockIVerificationTaskUpdateCall wrap *gomock.Call
type MockIVerificationTaskUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVerificationTaskUpdateCall) Return(arg0 error) *MockIVerificationTaskUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVerificationTaskUpdateCall) Do(f func(context.Context, *storage.VerificationTask) error) *MockIVerificationTaskUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVerificationTaskUpdateCall) DoAndReturn(f func(context.Context, *storage.VerificationTask) error) *MockIVerificationTaskUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
