// Code generated by MockGen. DO NOT EDIT.
// Source: verification_file.go
//
// Generated by this command:
//
//	mockgen -source=verification_file.go -destination=mock/verification_file.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	storage "github.com/baking-bad/noble-indexer/internal/storage"
	storage0 "github.com/dipdup-net/indexer-sdk/pkg/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockIVerificationFile is a mock of IVerificationFile interface.
type MockIVerificationFile struct {
	ctrl     *gomock.Controller
	recorder *MockIVerificationFileMockRecorder
	isgomock struct{}
}

// MockIVerificationFileMockRecorder is the mock recorder for MockIVerificationFile.
type MockIVerificationFileMockRecorder struct {
	mock *MockIVerificationFile
}

// NewMockIVerificationFile creates a new mock instance.
func NewMockIVerificationFile(ctrl *gomock.Controller) *MockIVerificationFile {
	mock := &MockIVerificationFile{ctrl: ctrl}
	mock.recorder = &MockIVerificationFileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIVerificationFile) EXPECT() *MockIVerificationFileMockRecorder {
	return m.recorder
}

// BulkSave mocks base method.
func (m *MockIVerificationFile) BulkSave(ctx context.Context, files ...*storage.VerificationFile) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range files {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BulkSave", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkSave indicates an expected call of BulkSave.
func (mr *MockIVerificationFileMockRecorder) BulkSave(ctx any, files ...any) *MockIVerificationFileBulkSaveCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, files...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkSave", reflect.TypeOf((*MockIVerificationFile)(nil).BulkSave), varargs...)
	return &MockIVerificationFileBulkSaveCall{Call: call}
}

// MockIVerificationFileBulkSaveCall wrap *gomock.Call
type MockIVerificationFileBulkSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVerificationFileBulkSaveCall) Return(arg0 error) *MockIVerificationFileBulkSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVerificationFileBulkSaveCall) Do(f func(context.Context, ...*storage.VerificationFile) error) *MockIVerificationFileBulkSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVerificationFileBulkSaveCall) DoAndReturn(f func(context.Context, ...*storage.VerificationFile) error) *MockIVerificationFileBulkSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ByTaskId mocks base method.
func (m *MockIVerificationFile) ByTaskId(ctx context.Context, id uint64) ([]storage.VerificationFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByTaskId", ctx, id)
	ret0, _ := ret[0].([]storage.VerificationFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByTaskId indicates an expected call of ByTaskId.
func (mr *MockIVerificationFileMockRecorder) ByTaskId(ctx, id any) *MockIVerificationFileByTaskIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByTaskId", reflect.TypeOf((*MockIVerificationFile)(nil).ByTaskId), ctx, id)
	return &MockIVerificationFileByTaskIdCall{Call: call}
}

// MockIVerificationFileByTaskIdCall wrap *gomock.Call
type MockIVerificationFileByTaskIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVerificationFileByTaskIdCall) Return(arg0 []storage.VerificationFile, arg1 error) *MockIVerificationFileByTaskIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVerificationFileByTaskIdCall) Do(f func(context.Context, uint64) ([]storage.VerificationFile, error)) *MockIVerificationFileByTaskIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVerificationFileByTaskIdCall) DoAndReturn(f func(context.Context, uint64) ([]storage.VerificationFile, error)) *MockIVerificationFileByTaskIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CursorList mocks base method.
func (m *MockIVerificationFile) CursorList(ctx context.Context, id, limit uint64, order storage0.SortOrder, cmp storage0.Comparator) ([]*storage.VerificationFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CursorList", ctx, id, limit, order, cmp)
	ret0, _ := ret[0].([]*storage.VerificationFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CursorList indicates an expected call of CursorList.
func (mr *MockIVerificationFileMockRecorder) CursorList(ctx, id, limit, order, cmp any) *MockIVerificationFileCursorListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CursorList", reflect.TypeOf((*MockIVerificationFile)(nil).CursorList), ctx, id, limit, order, cmp)
	return &MockIVerificationFileCursorListCall{Call: call}
}

// MockIVerificationFileCursorListCall wrap *gomock.Call
type MockIVerificationFileCursorListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVerificationFileCursorListCall) Return(arg0 []*storage.VerificationFile, arg1 error) *MockIVerificationFileCursorListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVerificationFileCursorListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.VerificationFile, error)) *MockIVerificationFileCursorListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVerificationFileCursorListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.VerificationFile, error)) *MockIVerificationFileCursorListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockIVerificationFile) GetByID(ctx context.Context, id uint64) (*storage.VerificationFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*storage.VerificationFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIVerificationFileMockRecorder) GetByID(ctx, id any) *MockIVerificationFileGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIVerificationFile)(nil).GetByID), ctx, id)
	return &MockIVerificationFileGetByIDCall{Call: call}
}

// MockIVerificationFileGetByIDCall wrap *gomock.Call
type MockIVerificationFileGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVerificationFileGetByIDCall) Return(arg0 *storage.VerificationFile, arg1 error) *MockIVerificationFileGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVerificationFileGetByIDCall) Do(f func(context.Context, uint64) (*storage.VerificationFile, error)) *MockIVerificationFileGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVerificationFileGetByIDCall) DoAndReturn(f func(context.Context, uint64) (*storage.VerificationFile, error)) *MockIVerificationFileGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsNoRows mocks base method.
func (m *MockIVerificationFile) IsNoRows(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNoRows", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNoRows indicates an expected call of IsNoRows.
func (mr *MockIVerificationFileMockRecorder) IsNoRows(err any) *MockIVerificationFileIsNoRowsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNoRows", reflect.TypeOf((*MockIVerificationFile)(nil).IsNoRows), err)
	return &MockIVerificationFileIsNoRowsCall{Call: call}
}

// MockIVerificationFileIsNoRowsCall wrap *gomock.Call
type MockIVerificationFileIsNoRowsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVerificationFileIsNoRowsCall) Return(arg0 bool) *MockIVerificationFileIsNoRowsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVerificationFileIsNoRowsCall) Do(f func(error) bool) *MockIVerificationFileIsNoRowsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVerificationFileIsNoRowsCall) DoAndReturn(f func(error) bool) *MockIVerificationFileIsNoRowsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LastID mocks base method.
func (m *MockIVerificationFile) LastID(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastID", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastID indicates an expected call of LastID.
func (mr *MockIVerificationFileMockRecorder) LastID(ctx any) *MockIVerificationFileLastIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastID", reflect.TypeOf((*MockIVerificationFile)(nil).LastID), ctx)
	return &MockIVerificationFileLastIDCall{Call: call}
}

// MockIVerificationFileLastIDCall wrap *gomock.Call
type MockIVerificationFileLastIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVerificationFileLastIDCall) Return(arg0 uint64, arg1 error) *MockIVerificationFileLastIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVerificationFileLastIDCall) Do(f func(context.Context) (uint64, error)) *MockIVerificationFileLastIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVerificationFileLastIDCall) DoAndReturn(f func(context.Context) (uint64, error)) *MockIVerificationFileLastIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockIVerificationFile) List(ctx context.Context, limit, offset uint64, order storage0.SortOrder) ([]*storage.VerificationFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset, order)
	ret0, _ := ret[0].([]*storage.VerificationFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIVerificationFileMockRecorder) List(ctx, limit, offset, order any) *MockIVerificationFileListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIVerificationFile)(nil).List), ctx, limit, offset, order)
	return &MockIVerificationFileListCall{Call: call}
}

// MockIVerificationFileListCall wrap *gomock.Call
type MockIVerificationFileListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVerificationFileListCall) Return(arg0 []*storage.VerificationFile, arg1 error) *MockIVerificationFileListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVerificationFileListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.VerificationFile, error)) *MockIVerificationFileListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVerificationFileListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.VerificationFile, error)) *MockIVerificationFileListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m_2 *MockIVerificationFile) Save(ctx context.Context, m *storage.VerificationFile) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockIVerificationFileMockRecorder) Save(ctx, m any) *MockIVerificationFileSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIVerificationFile)(nil).Save), ctx, m)
	return &MockIVerificationFileSaveCall{Call: call}
}

// MockIVerificationFileSaveCall wrap *gomock.Call
type MockIVerificationFileSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVerificationFileSaveCall) Return(arg0 error) *MockIVerificationFileSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVerificationFileSaveCall) Do(f func(context.Context, *storage.VerificationFile) error) *MockIVerificationFileSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVerificationFileSaveCall) DoAndReturn(f func(context.Context, *storage.VerificationFile) error) *MockIVerificationFileSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m_2 *MockIVerificationFile) Update(ctx context.Context, m *storage.VerificationFile) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIVerificationFileMockRecorder) Update(ctx, m any) *MockIVerificationFileUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIVerificationFile)(nil).Update), ctx, m)
	return &MockIVerificationFileUpdateCall{Call: call}
}

// MockIVerificationFileUpdateCall wrap *gomock.Call
type MockIVerificationFileUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVerificationFileUpdateCall) Return(arg0 error) *MockIVerificationFileUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVerificationFileUpdateCall) Do(f func(context.Context, *storage.VerificationFile) error) *MockIVerificationFileUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVerificationFileUpdateCall) DoAndReturn(f func(context.Context, *storage.VerificationFile) error) *MockIVerificationFileUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
