// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mock.go -package=cache -typed
//

// Package cache is a generated GoMock package.
package cache

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockICache is a mock of ICache interface.
type MockICache struct {
	ctrl     *gomock.Controller
	recorder *MockICacheMockRecorder
	isgomock struct{}
}

// MockICacheMockRecorder is the mock recorder for MockICache.
type MockICacheMockRecorder struct {
	mock *MockICache
}

// NewMockICache creates a new mock instance.
func NewMockICache(ctrl *gomock.Controller) *MockICache {
	mock := &MockICache{ctrl: ctrl}
	mock.recorder = &MockICacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICache) EXPECT() *MockICacheMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockICache) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockICacheMockRecorder) Close() *MockICacheCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockICache)(nil).Close))
	return &MockICacheCloseCall{Call: call}
}

// MockICacheCloseCall wrap *gomock.Call
type MockICacheCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockICacheCloseCall) Return(arg0 error) *MockICacheCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockICacheCloseCall) Do(f func() error) *MockICacheCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockICacheCloseCall) DoAndReturn(f func() error) *MockICacheCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockICache) Get(ctx context.Context, key string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockICacheMockRecorder) Get(ctx, key any) *MockICacheGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockICache)(nil).Get), ctx, key)
	return &MockICacheGetCall{Call: call}
}

// MockICacheGetCall wrap *gomock.Call
type MockICacheGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockICacheGetCall) Return(arg0 string, arg1 bool) *MockICacheGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockICacheGetCall) Do(f func(context.Context, string) (string, bool)) *MockICacheGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockICacheGetCall) DoAndReturn(f func(context.Context, string) (string, bool)) *MockICacheGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Set mocks base method.
func (m *MockICache) Set(ctx context.Context, key, data string, f ExpirationFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, data, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockICacheMockRecorder) Set(ctx, key, data, f any) *MockICacheSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockICache)(nil).Set), ctx, key, data, f)
	return &MockICacheSetCall{Call: call}
}

// MockICacheSetCall wrap *gomock.Call
type MockICacheSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockICacheSetCall) Return(arg0 error) *MockICacheSetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockICacheSetCall) Do(f func(context.Context, string, string, ExpirationFunc) error) *MockICacheSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockICacheSetCall) DoAndReturn(f func(context.Context, string, string, ExpirationFunc) error) *MockICacheSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
