name: Build
permissions:
  contents: read
  pull-requests: read
  packages: write

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE_BASE: ${{ github.repository }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Indexer
      - name: Indexer image tags & labels
        id: meta-indexer
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BASE }}/indexer

      - name: Indexer image build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/indexer/Dockerfile
          push: true
          cache-from: type=gha,scope=indexer
          cache-to: type=gha,mode=max,scope=indexer
          tags: ${{ steps.meta-indexer.outputs.tags }}
          labels: ${{ steps.meta-indexer.outputs.labels }}

      # API
      - name: API image tags & labels
        id: meta-api
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BASE }}/api

      - name: API image build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/api/Dockerfile
          push: true
          cache-from: type=gha,scope=api
          cache-to: type=gha,mode=max,scope=api
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}
